### ISSUE TITLE
Multiple servers starting up at the same time is causing them to share status

### ISSUE THREAD

**Issue by augustocdias** [j-hui/fidget.nvim#10]
The progress are being shared between all active LSP servers. See the print bellow.

![image](https://user-images.githubusercontent.com/1080789/151152973-fc48d0f3-3939-4422-886d-96651c50226f.png)

At some point I saw `summeko` saying it was running `cargo clippy`.

**Comment by mrjones2014** [comment]
Similar issue here, it's hard to tell which % line is for which server

![CleanShot-2022-01-26-at-06 45 10](https://user-images.githubusercontent.com/8648891/151157712-a9ca1c79-379c-4fa1-9e6b-70600098e8fa.png)

**Comment by gegoune** [comment]
Off topic: which version of sumneko LSP are you running? I am on 2.6.2 and no longer seeing any messages from it.

**Comment by mrjones2014** [comment]
I'm on 2.6.0 currently.

**Comment by dsully** [comment]
I'm seeing this as well.

**Comment by dsully** [comment]
Here's how I filter out duplicates:

https://github.com/dsully/dotfiles/blob/56a7eb3cdeed843aaeccb271bb0ff321d2ddff81/.config/nvim/lua/lsp/progress.lua

If that helps.

**Comment by j-hui** [comment]
I haven't implemented any filtering for duplicates just yet, but #18 makes it such that only notifications from an attached LSP server will show on the current buffer.

I suspect there may be some odd race conditions that cause issues like sumneko gaining clippy powers. I'll look into that next, but hopefully this at least makes it such that only relevant notifications are shown.

**Comment by wookayin** [comment]
I submitted a PR #30 that would fix this bug.
