### ISSUE TITLE
iTerm2 Cursor flickering while fidget is working

### ISSUE THREAD

**Issue by dustypaws** [j-hui/fidget.nvim#100]
I'm using fidget together with nvim 0.7.2 and iTerm2 and rust-analyzer. I'm just unsure if that's expected behaviour an issue with iTerm2 or something else. If I need to produce some logs or configuration files to help with tracking down the issue, I'm more than happy to do so. :)

My full nvim config: https://github.com/dustypaws/nvim.config
... just the fidget part: https://github.com/dustypaws/nvim.config/blob/master/lua/config/fidget.lua

**Comment by j-hui** [comment]
By flickering, do you mean that the cursor blinks erratically while the Fidget notifications are updating?

**Comment by dustypaws** [comment]
That’s what I mean yes. 😊

It’s no dealbreaker, it’s just a minor annoyance and I don’t know what’s causing it. 🤔🤷‍♂️

**Comment by dustypaws** [comment]
Basically it looks like this:

https://user-images.githubusercontent.com/19664015/188595569-88eba7ff-0d7f-4a78-9321-eee0601b5aac.mov

**Comment by j-hui** [comment]
After #143, this can be avoided somewhat by lowering the frame rate, or just disabling animations altogether. Please reopen if it's still a problem.
