### ISSUE TITLE
fold=indent changes fidget Title highlight

### ISSUE THREAD

**Issue by rodhash** [j-hui/fidget.nvim#102]
Hi

I didn't find a previous issue (found similar one, issue No31) so raising this one.

Issue:
When I have `foldmethod=indent` the FidgetTitle color changes at almost any key press, in the vid below I entered 3x in Insert mode and it changed the Title color. It makes the title match the same fold color.

For demonstration purpose I changed FidgetTitle to blue, just to give some contrast and easier to see the color change. We can see it starts as blue and suddenly changes to orange-ish.

https://user-images.githubusercontent.com/29671981/193287633-51eb08e3-a53d-4780-a4c9-caf8cf6addf1.mp4

I tried changing the "fdm" for Fidget Filetype window with no success.

Any suggestion?

ps: changing fdm to something else seems to solve the issue. However I'm curious if there's another option.

I'm using latest fidget `492492e` and Nvim `v0.8.0-dev-1081-g907fc8ac3`

Thank you

**Comment by j-hui** [comment]
I don't think I can reproduce this anymore, at least after the rewrite. Please re-open if this is still an issue.

**Comment by rodhash** [comment]
Agree, it no longer happens .. thanks
