### ISSUE TITLE
Doesn't work with mason

### ISSUE THREAD

**Issue by timsofteng** [j-hui/fidget.nvim#107]
I've installed tsserver with `Mason` plugin. Lsp server works as usual but fidget doesn't work with it...

**Comment by olimorris** [comment]
No issues for me. Must be your config

**Comment by machin3io** [comment]
Doesn't for for me either with pyright, installed via Mason. 
Does anybody have a solution?

**Comment by j-hui** [comment]
Can one of you share a config to reproduce the issue? I've not used mason before/am not sure what might be causing this issue.

**Comment by nyngwang** [comment]
@j-hui: Me. I have confidence that I have the simplest form of mason's config. Simply remove the content of the function `function (server_name)` and put your LSP setup code in it. (I just like the idea of importing them from other files)

```lua
  use {
    'neovim/nvim-lspconfig',
    requires = {
      'williamboman/mason.nvim',
      'williamboman/mason-lspconfig.nvim',
    },
    config = function ()
      -- ensure this order.
      require('mason').setup()
      require('mason-lspconfig').setup({
        ensure_installed = {
          'bashls',
            'dockerls',
          'sumneko_lua',
            'vimls',
          'tsserver',
            'eslint',
            'graphql',
            'jsonls',
            'cssls',
            'cssmodules_ls',
            'html',
          'clangd',
            'cmake',
          'diagnosticls',
          'pyright',
        },
      })
      require('mason-lspconfig').setup_handlers {
        -- fallback handler.
        function (server_name)
          local has_config, config = pcall(require, 'lsp_config.'..server_name)
          if not has_config then
            require('lspconfig')[server_name].setup(require('lsp_config.default'))
            return
          end
          require('lspconfig')[server_name].setup(config)
        end,
      }
    end
  }
```

**Comment by jtheoof** [comment]
If it helps, you can also have a look at my [nvim config](https://github.com/jtheoof/dotfiles/tree/master/.config/nvim) in my dotfiles. I'm having the same issue, the plugin was working fine until I started using Mason.

**Comment by carlosala** [comment]
For everyone, cannot reproduce. I was able to reproduce that but, trying to debug, saw that I had [arkav/lualine-lsp](https://github.com/arkav/lualine-lsp-progress) that was like owning that vim.lsp.handlers["$/progress"] function. Disabling that plugin makes everything work as expected.

**Comment by nyngwang** [comment]
FYI, [folke/noice.nvim](https://github.com/folke/noice.nvim) has a built-in `view='mini'`, which can achieve basically the same effect and it works with mason.nvim. Not saying that this is a better approach but that providing a workaround for those who don't want to wait.

**Comment by nyngwang** [comment]
@rensftw It's possible that what you see is the result of `mini` from noice.nvim.

**Comment by michelesr** [comment]
I just don't get it, I've tried to fiddle with it and it seems that the progress handler is setup correctly (it wraps the nvim runtime progress handler and then run fidget handler after), however, it doesn't seem to get triggered at all e.g. in `rust-analyzer`, while it works fine for the lua language server, but only if you try a big project such as telescope.nvim ... at this stage I can't understand whether rust-analyzer is broken and not triggering the handler or what else? I've installed the lua server with mason too, but maybe now is built in neovim too? I'm not sure

**Comment by michelesr** [comment]
Actually, I figured out what the problem was: some of the servers weren't configured correctly, you need to make sure to add the default capabilities and cmp ones if you use that too (have a look at kickstart.nvim as it's a good example of how is down): after doing that I managed to get all the supported servers working with fidget.nvim

**Comment by timsofteng** [comment]
@j-hui still doesn't work for me with Mason...
