### ISSUE TITLE
Change background

### ISSUE THREAD

**Issue by augustocdias** [j-hui/fidget.nvim#11]
Is it possible to add the possibility to add transparency or choose the color for the background? As you can see in the print bellow the background is quite different from the one from nvim.

![image](https://user-images.githubusercontent.com/1080789/151153224-25f88c20-144f-455f-923e-43c9bb1223de.png)

**Comment by j-hui** [comment]
For highlighting, I just link `FidgetTask` to `LineNr` and `FidgetTitle` to `Title`. Have you defined a background color for either of these?

You should now be able to override this highlight link following resolution of #6

**Comment by ahmedelgabri** [comment]
I tried this & still can't get rid of background.
<img width="222" alt="Screenshot 2022-01-26 at 23 22 51" src="https://user-images.githubusercontent.com/63876/151257283-e8e6eb59-2190-4fba-9c2b-4fa1627601e4.png">


```vim
hi! FidgetTitle ctermbg=NONE guibg=NONE
hi! FidgetTask ctermbg=NONE guibg=NONE
```

**Comment by j-hui** [comment]
Tha's odd. I'm not doing anything in my plugin to define the background color. If anything, I'm setting `winblend` to 100, so there really should be no background.

A few questions:

What does running `:hi FidgetTask` and `:hi FidgetTitle` show?

What colorscheme are you currently using?

Have you set `termguicolors`? If not, does the problem still persist with `set termguicolors`?

**Comment by augustocdias** [comment]
I get `FidgetTitle xxx links to Title` and `FidgetTask xxx links to NonText`.

I'm using [tokyo-night](https://github.com/folke/tokyonight.nvim) and `termguicolors` is set

**Comment by ahmedelgabri** [comment]
> What does running `:hi FidgetTask` and `:hi FidgetTitle` show?

Same as @augustocdias 

> What colorscheme are you currently using?

I'm using https://github.com/andreypopp/vim-colors-plain

> Have you set `termguicolors`? If not, does the problem still persist with `set termguicolors`?

Yes, I have it set.

**Comment by FollieHiyuki** [comment]
Issue transfered from #6, probably related:

My fidget appears darker or brighter than the defined colors on different buffers. Here are the screenshots:

![1](https://user-images.githubusercontent.com/67634026/151115843-26604a2e-8e46-4759-a3ff-7cf8a199499b.png)

![2](https://user-images.githubusercontent.com/67634026/151115912-fc623bbf-3900-450a-a87f-9b0e083f6ba9.png)

**Comment by mcauley-penney** [comment]
Setting winblend to 0 made my popup completely transparent. Kinda odd

![image](https://user-images.githubusercontent.com/59481467/151646914-d449e246-3feb-4cd1-a962-62411e0291b6.png)

**Comment by j-hui** [comment]
#23 (which superceded #22; thanks @axieax!) adds a `window.blend` option, among other things. Does this fix everyone's transparency issues?

**Comment by ahmedelgabri** [comment]
Yup, works fine for me. Thanks @j-hui

**Comment by FollieHiyuki** [comment]
I set `winblend = 0` and the colors seem ok now. Thanks!

**Comment by alex-popov-tech** [comment]
works for me with `{'j-hui/fidget.nvim', config = function() require('fidget').setup({ window = { winblend = 0 }}) end}`

**Comment by joshzcold** [comment]
For me I had to delete `packer_compiled.lua` before `winblend=0` would take effect. I guess in this case rerunning `PackerSync` `PackerCompile` is not enough. 

Thanks 👍

**Comment by joshzcold** [comment]
For future reference if you have `autocmd vimenter * hi Normal guibg=none guifg=none` in your config to make vim have a transparent background it will also cause figet to have a black background. 

Currently trying to find a way around this.

**Comment by prurph** [comment]
Is anyone still running into this? Regardless of what I've tried with highlight groups and the winblend option, the colors always appear much darker in fidget than they are in the actual theme/highlight setting. The background is transparent, however.

**Comment by Iskustvo** [comment]
Hi everyone!
Like @prurph, I can also often reproduce this issue (same as @FollieHiyuki [posted](https://github.com/j-hui/fidget.nvim/issues/11#issuecomment-1023868931), with dimmed highlights in some buffers, even for same instance of LSP/`fidget`), so I think it should be reopened.

I've been trying to analyze it for some time now and here is my summary (it might be useful to someone):
* I'm fairly certain that this issue cannot be reproduced unless `vim.opt.termguicolors = true` is set.
  (I have set this option manually and the [colorscheme](https://github.com/Mofiqul/vscode.nvim) I'm using also sets it internally. Unless I disable both the colorscheme AND my manual option, issue persists, even with default colorscheme.)
* Order of `vim.opt.termguicolors = true` and `fidget` setup doesn't seem to matter.
* In my experience, when issue is reproduced once (regardless of the used LSP and/or number of opened buffers), it is 100% reproducible by repeating the same thing over and over (i.e. opening Neovim with same files)
* Reproduction doesn't seem so consistent with different inputs, although it always looks the same visually.
  * When I open several (5-10) Lua files of my Neovim configuration, only first buffer has dimmed highlights for `sumneko_lua` LSP, while all others look as expected.
  * On the other hand, when I open 20+ C++ files with `clangd`, first few files always have correct `fidget` highlighting, while some of the later ones have dimmed highlighting.

While it also happened to me when opening just 1 Lua file with `sumneko_lua` LSP, I would suggest the following as best way to initially reproduce the issue:
* Make sure that your Lua configuration sets `vim.opt.termguicolors = true`.
* Optionally use default theme. (I don't think this matters, but it helps with narrowing the issue down.)
* Configure `fidget` to use default setup. (This should be easiest common ground for everyone and issue is reproducible with it.)
* Open all Lua configuration files for Neovim with `sumneko_lua` LSP. (Hopefully, this is something that all participants here have in common.)
* Quickly just browse through all of them with `:bnext` (or whatever keymap that is for you)
* Observer the `fidget` in the bottom right corner of the screen while browsing through files. Hopefully issue should be easily spotted.

**Comment by Iskustvo** [comment]
Silly me!
After reading #32, it became more apparent.
This issue actually happens when `fidget` is drawn below last line in file.

This makes reproduction easy:
* Position `fidget` at the bottom of the screen (also default).
* Open file which has all lines on the screen populated.
  Just empty lines are perfectly fine as long as there is something on the line (even just newline character).
* `fidget` should look as expected.
* Press `G` to jump at the bottom of the file.
* Press `zz` to center window to cursor position. This will position `fidget` below last line in the file.
* `fidget` will change colors when it finds itself below last line.

Maybe linking `fidget` highlights to some more persistent highlights (if there are such) by default would be better.

**Comment by jasonjurotich** [comment]
Still having a problem with this. Used everything below, but nothing happens. I would suggest just leaving blend as 0 in the future. 

use({
		"j-hui/fidget.nvim",
		config = function()
			require("fidget").setup({
				window = {
					blend = 0,
					relative = "editor",
				},
			})
		end,
		tag = "legacy",
	})

**Comment by mhdna** [comment]
> window = {
> blend = 0,
> relative = "editor",
> },

Try getting `blend = 0` out of the `window` scope:
```
blend=0,
window = {
    relative = "editor"
},
```
It worked for me.

**Comment by jayconnell** [comment]
Just in case anyone needs this - this is how I sorted the transparent background:
```
{
  "j-hui/fidget.nvim",
  opts = {
    notification = {
      window = {
        winblend = 0,
      },
    },
  },
},
```

**Comment by glwbr** [comment]
Just adding some information to this: 

#### **1. Behavior in Different Themes**  
- **RosePine**: If transparency is enabled, Fidget's background appears either black or white, depending on Neovim’s background color.  
- **Catppuccin**: No issues occur Fidget integrates correctly even when transparency is enabled.  

#### **2. Terminal Background and Fidget**  
- When using a **lighter terminal background** with transparency enabled, Neovim falls back to a white background, and Fidget adopts the same color as mentioned above.

#### **3. Terminal-Specific Behavior**  
- **Kitty**:  
  - If the theme has transparency disabled but Kitty itself has transparency value enabled, it makes neovim ignore the theme setting and remains transparent.  However, if transparency is disabled in both the theme and the terminal, Neovim remains opaque as expected.  This behavior is handled by some themes such as `Cattppuccin:` 
https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/palettes/init.lua) which fixes the colors

- **Alacritty**:  
  - Transparency is handled correctly—if the theme has transparency disabled (`false`), Neovim stays opaque even if the terminal background is transparent.  

#### **Workarounds**  
- In **Kitty**, you can disable transparency in the theme but enable it in the terminal, and Neovim will still appear transparent.  
- In **Alacritty** and possibly in other terminal, setting the `window.winblend = 0` option ensures proper behavior
