### ISSUE TITLE
How do I ignore a specified task message from a source

### ISSUE THREAD

**Issue by HUAHUAI23** [j-hui/fidget.nvim#112]
![image](https://user-images.githubusercontent.com/43649186/200856260-df3bb8d6-7fb7-4494-97d6-927fe94f64e4.png)
eg：i want to ignore code action messages from null-ls

**Comment by j-hui** [comment]
You should be able to ignore null-ls altogether with this option: https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.txt#L122

If you want to ignore a specific message, you can override the the `task` handler to look for `eslint` or `code_action` and return an empty string: https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.txt#L112  It's a little cumbersome and not well-tested but that's what I intended that handler for.

Closing this issue for now, but feel free to reopen if overriding the handler isn't sufficient.

**Comment by HUAHUAI23** [comment]
thank you for your answer, i have used task handler to ignore null-ls code-action message, but the fidget_name still exists, and i want to not display null-ls fidget_name when ignoring null-ls code-action message，how do i do that ?

**Comment by j-hui** [comment]
There's no good way to do that right now, unfortunately. The blunter
workaround for now is to ignore all null-ls progress messages altogether.
