### ISSUE TITLE
Doesn't work with sumneko-lua 3.6.3 (nix)

### ISSUE THREAD

**Issue by ghostbuster91** [j-hui/fidget.nvim#113]
Hi, 

First of all thanks for this great plugin!
After my latest update of nixpks the plugin stopped working (at least with sumneko-lua, that I am sure it worked before). 

My current versions where the plugin doesn't work are:
neovim: 0.8.1
fidget: `99b306167d1d305ca084e3bb475d6eadf32a365b` 
sumneko-lua: 3.6.3

Previous versions where it works:
neovim: 0.8.0
fidget: `1097a86db8ba38e390850dc4035a03ed234a4673`
sumenko-lua: 3.5.6

my minimized config is:
```
local lspconfig = require("lspconfig")

local capabilities = vim.lsp.protocol.make_client_capabilities()
local servers = { "bashls", "vimls", "rnix", "yamlls", "sumneko_lua" }
for _, lsp in ipairs(servers) do
        lspconfig[lsp].setup({
                capabilities = capabilities,
        })
end

require("fidget").setup()
```

After calling `LspInfo` I can see that the language-server was correctly attached to the buffer and diagnostics are showing.

```
:lua print(require"fidget".is_installed())
```
prints always `false` but I was told by some people on discord that it also works like that for them even though fidget works.

After calling 
```
:lua require"fidget".setup{}
```

nothing happens and previous command still prints `false`. 

I also tried with debug logging enabled but the log file doesn't exist.
```
cat ~/.local/share/fidget.nvim.log
cat: /home/kghost/.local/share/fidget.nvim.log: No such file or directory
```

Any ideas how I can debug it further?

**Comment by ghostbuster91** [comment]
So it seems that it might be just because the server is so fast that there is no point in displaying progress. https://github.com/sumneko/lua-language-server/issues/933

**Comment by j-hui** [comment]
@ghostbuster91 I'm able to see progress every time I open up my Lua Neovim configs.

Have you tried this with slower LSP servers or bigger projects?

**Comment by ghostbuster91** [comment]
@j-hui Yes, I've just opened telescope repository and it worked.
