### ISSUE TITLE
fidget not robust against weird buffer situations

### ISSUE THREAD

**Issue by al1-ce** [j-hui/fidget.nvim#115]
```
Error detected while processing BufUnload Autocommands for "*":                                                                                                                                             
E937: Attempt to delete a buffer that is in use: [No Name]
Press ENTER or type command to continue
Error detected while processing BufUnload Autocommands for "*":
Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:91: Error occured:
...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:325: Failed to unload buffer.
stack traceback:
        [C]: in function 'error'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:91: in function 'render_fidgets'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:223: in function 'fmt'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:476: in function <...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:475>
        [C]: in function 'wait'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:137: in function '_wait'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:156: in function 'run'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:47: in function 'reload_project'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:31: in function 'reload'
        ...m-tree.lua/lua/nvim-tree/actions/reloaders/reloaders.lua:41: in function 'reload_explorer'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:375: in function <...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:373>
        [C]: in function 'nvim_buf_delete'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:325: in function 'close'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:103: in function <...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:97>
        [C]: in function 'pcall'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:86: in function 'render_fidgets'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:223: in function 'fmt'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:476: in function <...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:475>
Press ENTER or type command to continue
```

Fidget config:
```
require("fidget").setup({
    window = {
        blend = 0
    }
})
```

Primarily error is present when switching from Alpha dashboard to any file and then switching to Nvim-tree

**Comment by al1-ce** [comment]
Wierdly running PackerUpdate solved the problem, but it still probably should check availability of buffer before unloading

**Comment by mbrc12** [comment]
Ran into the same problem just now, and `:PackerUpdate` seemed to solve the problem. I second @al1-ce 's suggestion of checking the buffer for availability.

**Comment by ehaynes99** [comment]
Based on that stack, I'm guessing it's related to this:

https://github.com/nvim-tree/nvim-tree.lua/commit/e14c2895b4f36a22001f7773244041c173dcf867

**Comment by al1-ce** [comment]
Still, fidget should probably do the same check

**Comment by Flo-Slv** [comment]
Hi there,

I have same issue and still occurs even after running :PackerUpdate command.

Is there a workaround to avoid this behaviour ? Because it happens a lot...

Thanks !

**Comment by Frostbitten-jello** [comment]
@Flo-Slv any solutions yet? having same issue

**Comment by Flo-Slv** [comment]
> @Flo-Slv found any solutions yet? having same issue
> 
> 

Nop.. sorry ! Still having this issue

**Comment by ehaynes99** [comment]
Check the actual version of nvim-tree.
```
cd ~/.local/share/nvim/site/pack/packer/start/nvim-tree.lua
git log
```
See if `e14c2895b4f36a22001f7773244041c173dcf867` is in the history (and/or that your version is newer than Mon Dec 17 17:19:00). If not, do you have a commit specified in your packer definition for `nvim-tree`?

**Comment by Frostbitten-jello** [comment]
> Check the actual version of nvim-tree.
> 
> ```
> cd ~/.local/share/nvim/site/pack/packer/start/nvim-tree.lua
> git log
> ```
> 
> See if `e14c2895b4f36a22001f7773244041c173dcf867` is in the history (and/or that your version is newer than [nvim-tree/nvim-tree.lua@e14c289](https://github.com/nvim-tree/nvim-tree.lua/commit/e14c2895b4f36a22001f7773244041c173dcf867)). If not, do you have a commit specified in your packer definition for `nvim-tree`?
> 
> EDIT: If that's not it, are you sure it's the same error, where `nvim-tree` is in the error trace?

Thanks a lot! the problem was the I had `tag = 'nightly' in my plugin use command, which I removed and then plugin updated to the new version. I thought nightly is supposed to be up to date as told in the readme

**Comment by j-hui** [comment]
I'm not ignoring this error explicitly in #143, but if it comes up after that is merged, please reopen.
