### ISSUE TITLE
"UI" issue when a box is empty

### ISSUE THREAD

**Issue by diegoulloao** [j-hui/fidget.nvim#116]
https://user-images.githubusercontent.com/45423661/210180251-6a3e48ed-839b-4d35-b23d-412547d0a79b.mov

When a box has no content (I guess it doesn't) is still there, so all that is displayed is an empty box where you can only see the top borders.

It disappears after some seconds.

**Comment by Baspar** [comment]
#119 should fix that issue

**Comment by j-hui** [comment]
Closed due to lack of activity.
