### ISSUE TITLE
What are the border options?

### ISSUE THREAD

**Issue by bushblade** [j-hui/fidget.nvim#123]
I see the documentation states...

> The value to use for the window border (see :h nvim_win_open), to adjust the Fidget window border style.
> 
> Type: string (default: "none")

But `:h nvim_win_open` doesn't have any help and outputs...

```
E149: Sorry, no help for nvim_win_open                                                                                                                                                                                                   
```

**Comment by bushblade** [comment]
Ah it should be `:h nvim_open_win`

**Comment by j-hui** [comment]
Thanks for spotting that! This should be fixed now.
