### ISSUE TITLE
Disable fidget in insert mode

### ISSUE THREAD

**Issue by mystilleef** [j-hui/fidget.nvim#125]
Depending on `lsp` servers, `fidget` can get very spammy and distracting. Is there a way to disable `fidget` in `InsertEnter`? An option or API to disable it in insert mode would help.

I've tried to detach the `lsp` clients from the buffer on `InsertEnter`. That works but many clients don't handle dynamically attaching and detaching clients without issues. So I've stopped using this workaround.

**Comment by GiuseppeMP** [comment]
@mystilleef I resolved a similar problem with this workaround: https://github.com/j-hui/fidget.nvim/issues/122#issuecomment-1509995748, may be useful.

**Comment by mystilleef** [comment]
@GiuseppeMP Unfortunately, that doesn't work for me. I still get lots of spam in insert mode, especially with the Haskell language server.

**Comment by GiuseppeMP** [comment]
> @GiuseppeMP Unfortunately, that doesn't work for me. I still get lots of spam in insert mode, especially with the Haskell language server.

In my case, the spam were of the task 'Validate Documents', perhaps Haskell is spamming another task and you need to change the if condition.

**Comment by j-hui** [comment]
Related: #126

**Comment by mystilleef** [comment]
Thanks!

For those who are wondering the API is as follows:

```lua
-- setup fidget
local fidget = require("fidget")
fidget.setup()

-- optional: if you want to use fidget notifications globally
vim.notify = fidget.notify

-- disable fidget
fidget.progress.suppress(true)
fidget.notification.suppress(true)

- enable fidget
fidget.progress.suppress(false)
fidget.notification.suppress(false)

```

You can use these in your `InsertEnter/InsertLeave` events in `aucmd` handlers to toggle fidget.
