### ISSUE TITLE
[Question] How to change spinner to moon?

### ISSUE THREAD

**Issue by niksingh710** [j-hui/fidget.nvim#128]
saw in a video so curious to know how can i change the spinner to moon emoji ?

**Comment by j-hui** [comment]
In your `setup` call, set the [`text.spinner`](https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.md#textspinner) to `"moon"`; other options are available [here](https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.md#spinners)
