### ISSUE TITLE
back background when transparency is enabled in colorscheme (tokyonight in my case)

### ISSUE THREAD

**Issue by vishytk** [j-hui/fidget.nvim#129]
My colorscheme configuration along with the screenshot of the issue. If I set the configuration option `transparent to false` it works fine.

How to resolve this issue such that the background of `fidget` adapts to when neovim background is set to transparent.

```lua
return {
  -- Colorscheme
  {
    'folke/tokyonight.nvim',
    lazy = false,
    priority = 1000,
    opts = {
      transparent = true,
    },
    config = function(_, opts)
      local tokyonight = require('tokyonight')
      tokyonight.setup(opts)
      tokyonight.load()
    end,
  },
}
```

![nvim-fidget](https://github.com/j-hui/fidget.nvim/assets/534818/9e409d9c-82d9-4a98-98d9-b91413810095)

**Comment by mijamarko** [comment]
Is your window.blend set to 0 in the fidget.nvim config? @vishytk

**Comment by envp** [comment]
> Is your window.blend set to 0 in the fidget.nvim config? @vishytk

Setting `window = { blend = 0 }` solved the interaction with transparent backgrounds, thanks!
