### ISSUE TITLE
Use vim.lsp.status() API instead of get_progress_messages

### ISSUE THREAD

**Issue by IndianBoy42** [j-hui/fidget.nvim#130]
https://github.com/neovim/neovim/pull/23958

**Comment by j-hui** [comment]
Related: c93c07c219bcf78c26b144027fcfd20cd23e55bd

**Comment by linrongbin16** [comment]
Hi, check my comment in [neovim#23958](https://github.com/neovim/neovim/pull/23958): https://github.com/neovim/neovim/pull/23958#issuecomment-1598037562
