### ISSUE TITLE
fidget.nvim will soon be rewritten. Please checkout the 'legacy' tag to avoid breaking changes.

### ISSUE THREAD

**Issue by noob2hero** [j-hui/fidget.nvim#138]
if i open a file by lvim, this error will be shown:
```
Installation in progress for [golangci_lint_ls]
fidget.nvim will soon be rewritten. Please checkout the 'legacy' tag to avoid breaking changes.
```
how can i fix it ? current branch is :
`"fidget.nvim": { "branch": "main", "commit": "89b633f3bd0b7187f070236b348697de176860e2" },`

**Comment by qwexvf** [comment]
@noob2hero 

as the doc says please use 'legacy' branch for now.

for lazy:
```
{
  "j-hui/fidget.nvim",
  tag = "legacy",
  event = "LspAttach",
  opts = {
    -- options
  },
}
```

for packer:
```
use {
  'j-hui/fidget.nvim',
  tag = 'legacy',
  config = function()
    require("fidget").setup {
      -- options
    }
  end,
}
```

**Comment by j-hui** [comment]
Related: #131

**Comment by nerdrew** [comment]
With a tag, it is a little awkward to update the checked out version. Can you do a `legacy` branch instead of a tag? Then I can update it regularly and when you've finally finished the re-write, you can change the message to "Switch back to main, the re-write is done!".
