### ISSUE TITLE
Tag="*' has been depreciated in Lazy.nvim

### ISSUE THREAD

**Issue by 035059** [j-hui/fidget.nvim#141]
Hello,

`tag = "*"`has been depreciated in Lazy.nvim in favor of `version = "*"`

the correct config for lazy should be
```  
{
  "j-hui/fidget.nvim",
  version = "legacy",
  config = function()
    require("fidget").setup()
  end,
},
```

The warning of the re-write is not suppressed by the correct Lazy config, and using tag results in a warning from lazy on neovim launch.

**Comment by boydkelly** [comment]
Very obnoxious.   I disabled fidget.

**Comment by j-hui** [comment]
@035059 can you point me to documentation indicating that `tag` is deprecated? I wasn’t able to find anything about this. 

In fact, folke seems to say the opposite: https://github.com/folke/lazy.nvim/issues/871

@boydkelly sorry you find it obnoxious.

**Comment by wookayin** [comment]
Can we just revert the legacy warning in the master branch? The development hasn't been done since the deprecation notice and it's only making noises. Any new, experimental development should be done in a non-default branch.
