### ISSUE TITLE
Support putting fidget window in top-right corner

### ISSUE THREAD

**Issue by cryptomilk** [j-hui/fidget.nvim#146]
Thanks for the rewrite.

It is currently not possible to change the position from bottom right to top right. It would be great if you could support changing the spinner position again. I've looked through the source code and couldn't find a wired config option for it.

**Comment by j-hui** [comment]
Yeah it’s not supported in the rewrite yet but I do plan on adding it back next. It should only require modifications to window.lua, with extra care taken about how the feature interacts with `y_offset`.
