### ISSUE TITLE
You can update the "Known to work with the following LSP servers" section to include `tsserver`

### ISSUE THREAD

**Issue by mrjones2014** [j-hui/fidget.nvim#15]
Amazing plugin, first of all. It's really great to have some visual feedback that work is happening and the LSP client isn't just frozen.

I've noticed it works great with `tsserver` (for Typescript) as well, if you want to add that to your "Known to work with the following LSP servers" section in the README.md.

**Comment by yanzhang0219** [comment]
It also works with golsp.

**Comment by j-hui** [comment]
Thanks! Yeah I've also since seen it working for clangd and haskell-language-server.

I think this information might accumulate in the main README, so I'll start an issue to track this information.

**Comment by j-hui** [comment]
I'm tracking this information here now: https://github.com/j-hui/fidget.nvim/issues/17, and now point there in the README
