### ISSUE TITLE
feat: bring back stack_upwards

### ISSUE THREAD

**Issue by j-hui** [j-hui/fidget.nvim#152]
Invert the order in which we stack notification items (and the group title); omitted in #143

**Comment by j-hui** [comment]
@0xAdk responding to https://github.com/j-hui/fidget.nvim/pull/158#issuecomment-1806991173 here (since I think this is the feature you're referring to?)

I think flipping the order of the lines needs be done in `notification/view`; otherwise, multi-line messages will get messed up.

If you'd like to take a crack at it, I'm happy to assign this issue to you (:

**Comment by 0xAdk** [comment]
I'll try

**Comment by j-hui** [comment]
Tip: use `require("fidget.logger").warn( etc )` for printing and tail the log in another window for debugging; at least for me this has been a lot less cumbersome than directly `print()`ing to Neovim's `:messages` buffer
