### ISSUE TITLE
feat: provide configuration option to override vim.notify

### ISSUE THREAD

**Issue by mystilleef** [j-hui/fidget.nvim#157]
For `lazy.nvim` users, can you provide an option to override `vim.notify`? 

That way we don't have to call `setup` manually and instead have `lazy` setup `fidget` for us. 

Right now I have to do this:

```lua 
{
  "j-hui/fidget.nvim",
  event = "VeryLazy",
  opts = {
    progress = {...}
  }
  config = function(_, opts)
      local fidget = require("fidget")
      fidget.setup(opts)
      vim.notify = fidget.notify
    end
}
```

With an `override_vim_notify` I can eliminate the setup process in `config`. Like so,

```lua
{
  "j-hui/fidget.nvim",
  event = "VeryLazy",
  opts = {
    progress = {...},
    notification = { override_vim_notify = true },
  }
}
```

**Comment by j-hui** [comment]
Great idea!

And please do keep me posted if any notifications get Fidget all bricked up... admittedly, I haven't been using it as a full vim.notify replacement myself just yet (but will now) so I'm sure there will be issues I haven't encountered yet.

**Comment by j-hui** [comment]
Oh god I already found something:

![image](https://github.com/j-hui/fidget.nvim/assets/11800204/0ce88bfd-9202-4adb-a49e-138650c87664)

When I was using Lazy with nvim-notify, nvim-notify was somehow rendering this as marked up text. I will need to figure out how to do that within Fidget's single notifications window...

**Comment by mystilleef** [comment]
I've moved away from `nvim-notify` in favor of `fidget.notify` as I find `nvim-notify` too distracting. 

I've overridden `vim.notify` with `fidget.notify` since yesterday and I've had no problems at all. 

Thanks for the update.
