### ISSUE TITLE
feat: deduplicate progress messages

### ISSUE THREAD

**Issue by j-hui** [j-hui/fidget.nvim#162]
Sometimes, an LSP server will start multiple tasks with the same message:
<img width="271" alt="image" src="https://github.com/j-hui/fidget.nvim/assets/11800204/11e5bd09-b075-4986-9986-c5d8ac46fb41">

It makes no sense for Fidget to display all of them.

**Comment by gegoune** [comment]
An idea: instead of hiding duplicates a counter, similar to one in browser's dev tools, could be displayed:

`(2x) Completed Building` (and then bump `x` counter on each repetition). What do you think?

**Comment by j-hui** [comment]
I like the counter idea a lot! I'm wondering though, what mechanism should we use for deduplication?

At the moment, deduplication happens by [`key` (which is the `token` accompanying each progress message)](https://github.com/j-hui/fidget.nvim/blob/main/lua/fidget/progress.lua#L122); my initial thought was to add an option to the progress subsystem that allows that to be overridden.

**Comment by mawkler** [comment]
I would love a deduplication feature as well. When using [ltex-ls](https://github.com/valentjn/ltex-ls) I get the notification "checking document" for **every keypress**, and they quickly start stacking:

![fidget-notifications](https://github.com/j-hui/fidget.nvim/assets/15816726/9dacea57-db7f-418f-9265-ec3b5d01d244)

**Comment by mawkler** [comment]
Works great, thank you!
