### ISSUE TITLE
The highlight groups set by `progress_style` and `done_style` appear to be reversed

### ISSUE THREAD

**Issue by leonasdev** [j-hui/fidget.nvim#165]
When I set following in `progress.display`:
```lua
done_style = "A",
progress_style = "B"
```
When the task is in progress, the highlight group of message is "A"; when the task done, the highlight group of message is "B".

These two seem to be reversed?

**Comment by j-hui** [comment]
Oops 🙄 just my silly color blindness issues

Thanks for spotting this! Should be fixed now.
