### ISSUE TITLE
Rust-analyzer initial building message stays until manually cleared

### ISSUE THREAD

**Issue by OleStrohm** [j-hui/fidget.nvim#167]
When opening a rust project with rust-analyzer the "In progress... Building" messages shows up (along with lots of other processes), and there's a progress bar looping. This is lovely, but the "In progress... Building" message and the progress indicator stick around forever.
I tried manually clearing it with `lua require("fidget").notification.reset()` and this manages to remove it, and it doesn't seem to reappear once the file is saved and other notifications show up.

I also tried saving the file to make other notifications show up while these two messages were still around, and the new messages come and go as expected, while these two stick around still.

Here is what it looks like after a long time:
![image](https://github.com/j-hui/fidget.nvim/assets/6892524/6856a787-b082-4bb7-944f-a77ae228c331)

Hopefully this is reproducible with a basic configuration, but if not, I'm happy to try and dig down to see if there's anything else in my config that might cause this interaction.

Thanks!

**Comment by OleStrohm** [comment]
I tried this with the minimal config in #156, and this problem still appears.
In fact looking at the gif in that PR it seems these two lines are about to stick around just like I'm seeing.

**Comment by j-hui** [comment]
I use rust-analyzer pretty regularly and definitely don’t have this issue. Can you reproduce this on a minimal Rust project, or at least a repo you can share?

**Comment by etrnal70** [comment]
I think this bus is rather intermittent. I got this yesterday while usually it's just fine

**Comment by j-hui** [comment]
It could be a bug on the LSP server side, i.e., it’s not sending the
corresponding completion message for some reason.

Another workaround, other than manually calling `reset()`, is to set a
really long but finite `progress_ttl` value and let zombie tasks garbage
collect themselves.

**Comment by OleStrohm** [comment]
I get it consistently when opening src/main.rs in https://github.com/OleStrohm/mp
Is there a way to see the message log to see if the completion message is missing? If so I can raise an RA bug.

Thank you for responding so quickly!

**Comment by acehinnnqru** [comment]
I also encountered this issue. But I can manually remove it by `lua require("fidget").notification.reset()`.

**Comment by j-hui** [comment]
@OleStrohm I just pushed 98047f3, which adds some logging. If you set the `logger.level = vim.log.levels.INFO`, you should be able to see the LSP progress messages in your log.

**Comment by OleStrohm** [comment]
Okay I managed to find the log with that patch and there is a
```
[INFO  Wed 15 Nov 2023 19:00:38 GMT] /lua/fidget/progress.lua:158: Notifying LSP progress message: {
  cancellable = false,
  done = false,
  lsp_id = 1,
  lsp_name = "rust_analyzer",
  title = "Building",
  token = "rustAnalyzer/Building"
}
```
But there is no corresponding "done" message for this, and I waited all the way until inlay hints showed up, so it should be done building by that point, especially compared to how quickly it disappears when opening other projects. I'll raise this with RA.

Thank you for helping!

**Comment by j-hui** [comment]
@OleStrohm  No problem!

For what it's worth: I just tried building `OleStrohm/mp`; after `cargo clean` and opening `src/main.rs`, the progress messages _eventually_ complete after 60s (I added timing info to the logging just now in f10103f):

```
[INFO  Wed Nov 15 14:14:08 2023] /lua/fidget/poll.lua:79: Poller ( notification ) stopping at 60.639s (duration: 60.102s) due to completion
```

And rust-analyzer seems to spend most of its time on `proc_macros`:

![image](https://github.com/j-hui/fidget.nvim/assets/11800204/b8b1f5e0-5578-43a9-80e5-34819a3ffd5d)

The fact that you only see `In progress...` (and not `building proc-macros: {etc}` like I do) suggests that our rust-analyzers are behaving differently. What version are you running? Here is mine:

```shell
$ rust-analyzer --version
rust-analyzer 1.73.0 (cc66ad46 2023-10-03)
```

> I'll raise this with RA.

Feel free to link the issue back here; I'm quite curious to know how this gets resolved (:

**Comment by OleStrohm** [comment]
I think I might be installing rust-analyzer nightly through my package manger or something, because I have:
```
$ rust-analyzer --version
rust-analyzer 1 (416e9c856 2023-11-12)
```
Yep, I'll link the issue back here!

I'll also try letting it load for a really long time and see if it ever resolves for me

**Comment by OleStrohm** [comment]
I'm unfortunately going to have to reopen this, as while attempting to fix the the issue in RA myself I added some extra logging, and it seems like it's working correctly:
```
Sending build progress: State: Begin, Message: None
Sending build progress: State: Report, Message: Some("building proc-macros: cfg-if")
...
Sending build progress: State: Report, Message: Some("building proc-macros: bevy")
Sending build progress: State: Report, Message: Some("building proc-macros: leafwing-input-manager")
Sending build progress: State: Report, Message: Some("building proc-macros: bevy_renet")
Sending build progress: State: Report, Message: Some("building proc-macros: mp")
Sending build progress: State: Report, Message: Some("building proc-macros: mp")
Sending build progress: State: End, Message: None
```
As you can see the End message is indeed sent, and yet it seems fidget isn't receiving it properly

**Comment by OleStrohm** [comment]
Also regarding the "In Progress... message", that is indeed strange, but the messages do seem to have proper messages (as you can see from above), but I only see the "In Progress..." message in the mp repo. In the rust-analyzer repo I do see the "building proc-macros: hir-ty" etc, though it still gets stuck, and never seems to recover even after 5+ minutes for me

**Comment by j-hui** [comment]
I'm assuming you're doing this logging from RA side?

On Fidget side, you can try adding some logging to the LSP progress message [polling loop](https://github.com/j-hui/fidget.nvim/blob/main/lua/fidget/progress/lsp.lua#L20-L43) (or [here](https://github.com/j-hui/fidget.nvim/blob/main/lua/fidget/progress/lsp.lua#L88C10-L125) if you're not on Neovim nightly). That's reading directly from the messages logged by Neovim's [builtin progress handler](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/handlers.lua#L23-L57) ([different on stable](https://github.com/neovim/neovim/blob/v0.9.4/runtime/lua/vim/lsp/handlers.lua#L23-L67)). Please let me know if you're picking up the `end` message sent from RA, or the progress report messages.

Also, can you try this with a stable/non-nightly build of RA?

**Comment by OleStrohm** [comment]
To clarify, I am logging this at the final point of sending messages from RA across the LSP communication channel. I am already a bit surprised that I only had one message in the Fidget log (as there should be like 100+ intermediate progress reports in addition to the start and end), so I have been looking at the code, but it doesn't seem like it should affect it, so maybe something is happening in the LSP layer.

I'll try to experiment with further logging over the next few days to see if I can find out where the message gets lost, thanks for the tips!

Will post another message if I manage to figure out the root of this :)

**Comment by OleStrohm** [comment]
Alright so I managed to find a solution, but I don't quite know what the original code is intending to do, but I created a patch that resolves this issue for me locally (in fact I no longer even see any messages about this because it's so quick to finish)

I suspect that what was happening (based on how clumped even the LspLog is) is that it's sending so many messages that it's overloading the ringbuffer of progress updates.

I have a relatively small patch here to hack in this functionality. I can create a PR for this, but I'm bypassing all the logic you have to do with polling, and I don't know the implications of that.
Anyway, the patch is here:
https://github.com/OleStrohm/fidget.nvim/commit/4746d11fa041c1676b459a6a7655bb0e8726b86e

If you think this makes sense then I'll create a PR of a cleaned up version of this, if not then maybe you can rework this into something that does resolve things.

**Comment by j-hui** [comment]
Ok if RA is blasting neovim with 100+ progress messages, then the ring buffer is definitely overflowing, since it’s sized at 50: https://github.com/neovim/neovim/blob/326d46f690b383846f136f2a25523cffe2882f27/runtime/lua/vim/lsp.lua#L1323 

There are two ways you can verify that this overflow is the culprit:
(1) revert to nvim stable (0.9.4), which does not use the ring buffer, or (2) hack the LSP handler and assign a ringbuf with, say, 2000 empty slots. (Neither is a long-term solution, but will confirm this hypothesis.)

As for your patch, having an event-driven LSP progress handler is certainly possible (that’s what legacy Fidget used to do). But I’d like to get to the bottom of the this overloading hypothesis before rolling that out as a fix.

**Comment by OleStrohm** [comment]
Sorry for getting back to you so late, but I just managed to try out the code snippet you provided and that does indeed resolve the problem, so it seems the issue is that RA is sending too many messages for neovim to handle.

**Comment by j-hui** [comment]
All good, I'm glad that fixed it for you.

For now, I've added the `progress.lsp.progress_ringbuf_size` option in [5be956d](https://github.com/j-hui/fidget.nvim/commit/5be956d940d3ebeb7ea04289382117876c68ce13) to make that ringbuf thing a little easier to configure (imo it's not really Fidget's job to manage nvim LSP internals, but this is a quick fix for now; I might deprecate this option later if nvim's LSP progress ringbuf ever changes).

At least with [OleStrohm/mp](https://github.com/OleStrohm/mp), setting the ringbuf_size to 1024 seemed to fix things for me (oh yeah, I was able to reproduce your issue with a nightly nvim build). You may need a bigger size for bigger projects.

**Comment by OleStrohm** [comment]
Thank you so much, I'll update to that an set it to a reasonably high number.

Thanks for opening the neovim issue as well

Loving the plugin btw!
