### ISSUE TITLE
Known compatible LSP servers

### ISSUE THREAD

**Issue by j-hui** [j-hui/fidget.nvim#17]
This plugin is known to work with the following LSP servers:

- [rust-analyzer](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rust_analyzer) (Rust)
- [sumneko](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sumneko_lua) (Lua)
- [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) (generic)
- [gopls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#gopls) (Go [[*issue]](https://github.com/j-hui/fidget.nvim/issues/19))
- [tsserver](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver) (Typescript, Javascript [[*caveat]](https://github.com/j-hui/fidget.nvim/issues/17#issuecomment-1037164904))
- [hls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#hls) (Haskell)
- [clangd](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd) (C, C++, Objective-C)
- [pyright](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#pyright) (Python)
- [kotlin-language-server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#kotlin_language_server) (Kotlin)
- [dartls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#dartls) (Dart [[*does not work with flutter-tools.nvim]](https://github.com/j-hui/fidget.nvim/issues/17#issuecomment-1046054946))
- [erlangls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#erlangls) (Erlang)
- [solargraph](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#solargraph) (Ruby)

And doesn't (yet) work with the following:

- [jdtls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#jdtls) (Java [see #57])
- [elixirls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#elixirls) (Elixir)

Please comment below if you find this plugin works or doesn't work with an LSP server you use.

----

Note that fidget's implementation relies on my cursory and incomplete understanding of the [progress notification spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workDoneProgress). Please file a separate issue if you think there's something I missed. 

However, if language servers actually deviate from spec, then this plugin will not know how to handle that. Please also file an issue in this repo for these cases. 

Ideally we should never terminate ungracefully, and have some kind of sane behavior for handling these cases. For example, if a server never sends an end progress notification, then the fidget will remain stuck onscreen. 

At the same time, if language servers do not appear to be conforming to LSP, we should file an issue with their maintainers, if anything but to clarify what the behavior is.

**Comment by yanzhang0219** [comment]
For `tsserver`, I find this plugin works great with TypeScript, but not JavaScript. I tested it by opening a file in a JavaScript repo, but nothing was shown up.

**Comment by mrjones2014** [comment]
hm, @yanzhang0219 I don't have that issue. It works the same for me in Javascript files.

**Comment by yanzhang0219** [comment]
@mrjones2014 could you please provide the js repo? I want to test it on my end. Thanks

**Comment by mrjones2014** [comment]
I just tested it with a proprietary repo I had open at work. But testing a little further, it seems like there is an issue when there is _only_ Javascript. It worked when I opened a Javascript file in a project which also contains Typescript files.

But I tested again with https://github.com/mrjones2014/eslint-plugin-storage and was able to reproduce the issue, actually.

**Comment by yanzhang0219** [comment]
Yes! That's what I was saying. Pure js repo has the issue.

**Comment by yanzhang0219** [comment]
I tested `lsp-status.nvim` just now and it didn't show any progress for the pure js repo. So I think it totally depends on the server. If the server doesn't return progress information to Neovim core lsp client, this plugin can do nothing. Am I correct? @j-hui

**Comment by j-hui** [comment]
> If the server doesn't return progress information to Neovim core lsp client, this plugin can do nothing. 
Yeah that's exactly right.

**Comment by gegoune** [comment]
This is what I was thinking from the very beginning. I am not sure if there is need for specifying which servers it works with, it's up to the server to send messages and this plugin cannot do anything extra to ensure compatibility with specific servers. Isn't it correct?

Great plugin, having messages in status line never sat well with me. Your plugins employs such a simple yet beautiful idea, well done!

**Comment by j-hui** [comment]
Thanks @gegoune !

> I am not sure if there is need for specifying which servers it works with, it's up to the server to send messages and this plugin cannot do anything extra to ensure compatibility with specific servers. Isn't it correct?

Perhaps not, but a few people had asked about this information, so I figured it's worth accumulating this knowledge somewhere.

Also, while LSP defines the [progress endpoint](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#progress), it doesn't seem to say anything about the format with which servers should report progress. For example, right now I assume that each progress notification comes with a `message` field and a `title` field. I want to keep this issue to help me keep track of different schemas different language servers may employ.

**Comment by polyzen** [comment]
Works with `pyright` as well.

**Comment by crisidev** [comment]
I am using this also with kotlin (https://github.com/fwcd/kotlin-language-server) and works properly. FYI the kotlin-language-server takes a lot to startup, so fidget starts around 30 seconds after opening the first file of the session

**Comment by Slotos** [comment]
[Solargraph](https://github.com/castwide/solargraph) (Ruby LSP) works. Server itself can take a few seconds to start sending messages, especially on larger projects.

**Comment by cjnucette** [comment]
> Yes. That's what I was saying. Pure js repo has the issue. Let me test your repo now.
> 
> UPDATE: it is confirmed that it doesn't work with pure js repo.

You need either a tsconfig.json or a jsconfig.json file on your project for it to work.

**Comment by fitrh** [comment]
`dartls` with lspconfig works fine, but [flutter-tools.nvim](https://github.com/akinsho/flutter-tools.nvim) does not, is there some modification ? I'm not familiar with LSP specs

**Comment by HiPhish** [comment]
Works out of the box with [erlang-ls](https://erlang-ls.github.io/) for me, tested with version 0.23.1.
![Screenshot_20220219_142025](https://user-images.githubusercontent.com/4954650/154802698-5472533b-fdd6-49bf-bcd9-39bf2781400b.png)

**Comment by j-hui** [comment]
@fitrh flutter-tools.nvim appears to install their own progress handler, which will override Fidget's: https://github.com/akinsho/flutter-tools.nvim/blob/3f3b16d69cdd26e2ed1b2baa719abac7f4c1a8b1/lua/flutter-tools/lsp/init.lua#L85

**Comment by fitrh** [comment]
@j-hui does this [line](https://github.com/akinsho/flutter-tools.nvim/blob/3f3b16d69cdd26e2ed1b2baa719abac7f4c1a8b1/lua/flutter-tools/lsp/init.lua#L52) mean they still call the default handler so other plugin can use it ? I tried using [arkav/lualine-lsp-progress](https://github.com/arkav/lualine-lsp-progress) and it seems they can catch the progress from `flutter-tools.nvim`

**Comment by fitrh** [comment]
@j-hui `dartls` with `flutter-tools.nvim` works, seems like a lazy loading issue

**Comment by mrnovalles** [comment]
this plugin does not work with `elixirls` at the moment. I'd be willing give the fix a try, but I am completely new to all of it

**Comment by Slotos** [comment]
> this plugin does not work with `elixirls` at the moment. I'd be willing give the fix a try, but I am completely new to all of it

It doesn't seem like elixir-ls implements [workDoneProgress](https://microsoft.github.io/language-server-protocol/specification#initiatingWorkDoneProgress) Without it, there's no data for fidget to report.

You can monitor LSP exchange by setting `vim.lsp.set_log_level("debug")` and tailing `~/.cache/nvim/lsp.log`. Sumneko or Solargraph will initiate startup progress report with something akin to:

```
[DEBUG][2022-03-23 18:46:56] .../vim/lsp/rpc.lua:454	"rpc.receive"	{  id = 9,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = 2  }}
[DEBUG][2022-03-23 18:46:56] .../vim/lsp/rpc.lua:454	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      cancellable = false,      kind = "begin",      message = "46/511",      percentage = 9,      title = "Loading workspace"    }  }}
[DEBUG][2022-03-23 18:46:56] .../vim/lsp/rpc.lua:454	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "48/511",      percentage = 9    }  }}
[DEBUG][2022-03-23 18:46:57] .../vim/lsp/rpc.lua:454	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "53/511",      percentage = 10    }  }}
```

ElixirLs doesn't initiate this reporting and I can't find any mention of `workDone` in its or it dependencies code.

**Comment by benjstephenson** [comment]
Looks like omnisharp doesn't work at the moment, I'd be keen to give it a try though.

**Comment by jsholmes** [comment]
This says it works with clangd, but it doesn't seem to for me.  Is there something extra I need to add to the clangd config?  I'm already doing `clangdFileStatus = true` in the `init_options`

**Comment by zer0-x** [comment]
It doesn't seem to work with `jedi-language-server` for python.

**Comment by asteroidalaz** [comment]
> 

It works in Cmake project, with compiled_commands.json. If you have makefile project, then try creating compiled_commands.json, using some tool.

**Comment by fitrh** [comment]
> It works in Cmake project. If you have makefile project, then shift to "Cmake project"

No, with [this config](https://github.com/fitrh/init.nvim/blob/main/lua/config/lsp/server/clangd.lua) even makefile project works for me, I think all we need is `init_options.clangdFileStatus = true`

**Comment by j-hui** [comment]
@jsholmes @asteroidalaz @fitrh it definitely works with Clangd, regardless of build system (make vs clangd). I use fidget with clangd daily. 

What matters is you need to have your build system generate a compile_commands.json to tell clangd what what flags you're compiling each file with. Iirc cmake happens to know how to generate these out of the box; for Makefiles, you'll need the help of a tool like bear.

If you are still having trouble with clangd (or any other language server), first verify that you are able to get other LSP features working (e.g., see if go to definition works). If it still doesn't work, open an issue. This issue is not for troubleshooting specific LSP setups; it is for discussing whether language servers provide progress notifications _given that they already work otherwise_.

**Comment by jsholmes** [comment]
@j-hui , clangd works well for me in all other LSP-related activities.  goto definition, code completion via cmp, lsp-saga works, etc.  It is only fidget that dosen't seem to work with clangd.

Note, i do *not* have compile_commands,json.  Instead, I use compile_flags.txt.  (see https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clangd/Installation.html).  Perhaps this is the issue?

**Comment by kataklasm** [comment]
Unfortunately I can't get fidget to work with Julia, even though LanguageServer.jl sends workDoneProress according to some issues over there.

**Comment by CalebDW** [comment]
This works with [phpactor](https://github.com/phpactor/phpactor)(PHP).

**Comment by davidelias** [comment]
> ElixirLs doesn't initiate this reporting and I can't find any mention of `workDone` in its or it dependencies code.

There's already an issue reported: https://github.com/elixir-lsp/elixir-ls/issues/848

Meanwhile, you can try this hack as a temporary solution:
```
local on_log_message = function(err, result, ctx, config)
  vim.lsp.handlers['window/logMessage'](err, result, ctx, config)

  -- Only do it for info/log type logs
  if result.type > 2 then
    local opts = { client_id = ctx.client_id }
    local token = tostring({}):sub(10) -- random string hack

    vim.lsp.handlers['$/progress'](nil, {
      token = token,
      value = { kind = 'begin', title = result.message }
    }, opts)

    vim.lsp.handlers['$/progress'](nil, {
      token = token,
      value = { kind = 'end' }
    }, opts)
  end
end

require('lspconfig').elixirls.setup({
  ...
  handlers = {
    ['window/logMessage'] = on_log_message,
  },
  ...
})

```

**Comment by j-hui** [comment]
I'm closing this issue in favor of [this Wiki page](https://github.com/j-hui/fidget.nvim/wiki/Known-compatible-LSP-servers). I've also updated it to include some of the newer messages I missed.

And for the sake of navigability, it's probably a good idea to file separate issues (or discussions?) to bring this up. (Man, implementing a Wiki using a pinned issue was such a bad idea...)

**Comment by j-hui** [comment]
By the way, @davidelias can you please test whether your workaround still works(around)?

If so, I will add it to the Wiki page.

**Comment by rudiejd** [comment]
This doesn't work with [csharp-ls](github.com/razzmatazz/csharp-language-server). I'll see if I can get it working
