### ISSUE TITLE
Spinner Customization

### ISSUE THREAD

**Issue by AndreM222** [j-hui/fidget.nvim#170]
Is it possible to use custom spinners? if so how can I set up mine? I wanted to set this one.

{ "󰨔", "󰕞", "󰕣", "󱡗", "󱡖", "󱡗", "󰕣", "󰕞" }

**Comment by AndreM222** [comment]
progress_icon = { pattern = { "󰨔", "󰕞", "󰕣", "󱡗", "󱡖", "󱡗", "󰕣", "󰕞" } },

**Comment by j-hui** [comment]
Glad you figured it out!

Related: #161
