### ISSUE TITLE
feat: change Fidget window border color

### ISSUE THREAD

**Issue by diegoulloao** [j-hui/fidget.nvim#174]
Sorry for opening this, but I'm not able to find how to change the border color.

<img width="374" alt="Screenshot" src="https://github.com/j-hui/fidget.nvim/assets/45423661/bbf37d0f-820f-439f-a2a4-f9daddb20e89">

**Comment by j-hui** [comment]
For now, Fidget does not support configuring its own border color.

You can customize the border color globally by setting the `FloatBorder` highlight group (though this will change the color of all borders).

**Comment by diegoulloao** [comment]
Nice! that works.

I leave the solution (just in case):
```lua
-- general/fidget border color
vim.cmd([[ hi! FloatBorder guibg=NONE guifg=#FFB454 ]])
```

**Comment by diegoulloao** [comment]
@j-hui, one more question, what about the text color?

**Comment by j-hui** [comment]
You can use the `notification.window.normal_hl` option to choose which highlight group is used (see docs for more details).

**Comment by mrdandelion6** [comment]
```lua
config = function()
          require('fidget').setup {
            notification = {
              window = {
                normal_hl = '',
                winblend = 0,
                border = 'rounded',
                border_hl = 'FidgetBorder',
                relative = 'win',
              },
              view = {
                stack_upwards = true,
                icon_separator = ' ',
                group_separator = '---',
                group_separator_hl = 'Comment',
              },
            },
          }

          -- change border color
          vim.api.nvim_set_hl(0, 'FidgetBorder', { fg = '#f0a4d0', bg = 'NONE' })
        end,
```
