### ISSUE TITLE
fidget.nvim stopped working with tsserver

### ISSUE THREAD

**Issue by leiswatch** [j-hui/fidget.nvim#176]
Hey, I noticed that fidget doesn't show the popup on the bottom right of the editor for tsserver after recent updates. I can confirm, that it works fine with changes in this commit 2dfaf28c4738e91fe2363ad2d19b36c87ab3b4c6, but doesn't work with changes afterward. Could you please take a look? I'm using default configuration.

**Comment by j-hui** [comment]
Thanks for noticing so soon! Can you provide me a basic typescript/javascript repo that I can use to try to reproduce the issue?

**Comment by leiswatch** [comment]
@j-hui Thanks for the quick response. I can reproduce it in very simple and minimal repo (assuming you have `node` and `npm` installed)

`mkdir test && cd test`
`npm init -y`
`npx tsc --init`
`nvim main.ts`

For the record I'm on node 20.10.0 (lts), npm 10.2.3, neovim 0.9.4.

**Comment by fitrh** [comment]
This is may be a language-server issue

**Comment by leiswatch** [comment]
@fitrh @j-hui I can confirm that settings `progress.ignore_empty_message` to `false` resolved my issue. Thank you very much!

**Comment by j-hui** [comment]
I finally found some time to test this out (thanks for the easy-to-follow instructions @leiswatch!) and get to the bottom of this.

Here's an example of a progress message being sent from the TS language server:

```lua
{
  cancellable = false,
  done = true,
  lsp_id = 1,
  lsp_name = "tsserver",
  title = "Initializing JS/TS language features…",
  token = "0fe4b117-c0f7-4d48-96b5-324d6ce3c40a"
}
```

There's no `message`, so those messages were being dropped. And that's also why the fix @fitrh  suggested works.

I think this is a good argument in favor of making `ignore_empty_messages = false` by default (after all, there's no requirement that progress notifications have to carry a message). I shall do that soon.
