### ISSUE TITLE
feat: progress messages for uninitialized clients

### ISSUE THREAD

**Issue by j-hui** [j-hui/fidget.nvim#177]
Continuing discussion of #139 here (this is no longer specific to ClojureLSP).

@Samy-33:

> Hey John, do `active clients` mean the attached clients?
>
> If so, it won't return clojure LSP as it's not yet attached ( but still sending `$/progress` messages, which is allowed by the spec).

Yeah, just like Neovim's [`vim.lsp.status()`](https://github.com/neovim/neovim/blob/18b19957b65be4f5e3b223b89a9a77458276fb5c/runtime/lua/vim/lsp.lua#L894) function, I call `vim.lsp.get_clients()`, which only looks for [active clients](https://github.com/neovim/neovim/blob/18b19957b65be4f5e3b223b89a9a77458276fb5c/runtime/lua/vim/lsp.lua#L2052-L2053).

At the moment, I don't know of any mechanism for iterating through all clients, including uninitialized ones. I will a file an issue upstream to see if this is possible.

**Comment by j-hui** [comment]
@Samy-33 I've finally got around to trying to reproduce your issue (i.e., progress messages on yet-to-be-initialized LSP client). However, I've had no luck: `clojure-lsp` does not appear to be sending anything.

I followed your instructions + enabled ClojureLSP using nvim-lspconfig, but I do not see any progress messages from `clojure-lsp` at all (I overrode the `$/progress` handler using the snippet I wrote before). But it does seem to be working, insofar as showing me these error messages about missing `http-server`:

![image](https://github.com/j-hui/fidget.nvim/assets/11800204/75fe17f6-0c07-4161-bd9a-29a936e212e6)

Here are the versions I have, on macOS:

```console
$ java --version
openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment Homebrew (build 21.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)
$ lein --version
Leiningen 2.10.0 on Java 21.0.1 OpenJDK 64-Bit Server VM
$ clojure-lsp --version
clojure-lsp 2023.10.30-21.15.51-nightly
clj-kondo 2023.10.21-SNAPSHOT
```

Have you still been having this issue lately?

**Comment by Samy-33** [comment]
@j-hui, thanks for taking the time to reproduce the issue.

I think, we're missing a `workDoneToken`. clojure-lsp doesn't return anything unless we manually send the token in the `initialise` request.

We need to hook a function that updates params sent in initialise token like this: https://github.com/Samy-33/dotfiles/blob/master/dotcom/.config/nvim/fnl/user/config/lsp.fnl#L62-L65C64

Lua equivalent (but autogenerated): https://github.com/Samy-33/dotfiles/blob/master/dotcom/.config/nvim/lua/user/config/lsp.lua#L50-L57

**Comment by Samy-33** [comment]
I see an interesting implementation here: https://github.com/rafaeldelboni/cajus-nfnl/blob/main/.config/nvim/fnl/config/lsp.fnl

Maybe it'll help you with some ideas.
