### ISSUE TITLE
Encountered unknown options during setup(): unknown option: progress.ignore_empty_message

### ISSUE THREAD

**Issue by TheJasonPlayz** [j-hui/fidget.nvim#179]
Hello!
I was trying to write my configuration using [lazy.nvim](https://github.com/folke/lazy.nvim). I was getting a lot of "In progress... WARN" messages [#295 haskell-tools](https://github.com/mrcjkb/haskell-tools.nvim/issues/295) and I was trying to fix it. When I used the following config, it did not do anything and instead gave me an error that there was an unknown option. Any help? Thank you!
Jason

**plugins.lua**
`{ "j-hui/fidget.nvim", opts = { progress = { ignore_empty_message = true } } },`

**Comment by j-hui** [comment]
Can you please confirm that your Fidget is up to date?

**Comment by daneski13** [comment]
I'm having a similar issue and I'm on the latest commit:
```
[WARN  Thu Nov 23 19:52:48 2023] /lua/fidget.lua:20: Encountered unknown options during setup():
[WARN  Thu Nov 23 19:52:48 2023] /lua/fidget.lua:22: - unknown option: window
```

I think a more recent update caused the issue because it stopped working after I did an update haven't changed my config in ages except for swapping `blend` for `winblend` since I noticed that API change during my troubleshooting:
```
fidget = require("fidget")
fidget.setup({
	window = {
		winblend = 0,
	},
})
```

**Comment by j-hui** [comment]
@daneski13 , the version of Fidget you're using has been completely written as of https://github.com/j-hui/fidget.nvim/pull/143.

In the rewrite, the equivalent option is:

```lua
{ notification = { window = { winblend = 0 } } }
```

**Comment by j-hui** [comment]
@TheJasonPlayz are you still encountering this issue? If not, I will close it.
