### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by j-hui** [j-hui/fidget.nvim#188]
@willothy let's continue the discussion here, continued from #178 

>> Oh I'd love that 😍 It's been on my TODO list but I haven't gotten around to it yet. (The possibility of testing was one of the reasons behind me splitting up the plugin into separate progress and notifications subsystems, and also maintaining a notifications view/abstract state separate from the window).
>
> Cool, sounds good! Do you have a preference for plenary vs. mini for test framework?

I'd only looked at plenary before, so I was planning on using that. But if there's a good reason to use mini, I'm open to that too; I don't have a strong preference for either.

**Comment by willothy** [comment]
Plenary works then, I don't have a preference either.
