### ISSUE TITLE
vim.lsp.get_clients() does not exists

### ISSUE THREAD

**Issue by Pedro-Nicolas-Rios-Vargas** [j-hui/fidget.nvim#206]
I recently updated my plugins manager to Lazy, and made some changes on different plugins, I notice that Fidget has changed it's configuration and I decided to implement the default config you share in the README.
![lazy_plug_conf](https://github.com/j-hui/fidget.nvim/assets/36179716/b6970f7d-eea6-4782-87db-dc25da3d43ac)

The error comes from _lua/fidget/progress/lsp.lua:61_, I search the function in lsp documentation and it is not mentioned anywhere.
![fidget_error](https://github.com/j-hui/fidget.nvim/assets/36179716/ad871154-d767-4162-bc38-fddd22474705)

**Comment by j-hui** [comment]
Thanks for reporting this. What version of nvim are you in?

**Comment by Pedro-Nicolas-Rios-Vargas** [comment]
NVIM v0.10.0-dev-531+g4e63104c4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/ordep/repos/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/ordep/repos/neovim/.deps/usr/include -I/home/ordep/repos/neovim/build/src/nvim/auto -I/home/ordep/repos/neovim/build/include -I/home/ordep/repos/neovim/build/cmake.config -I/home/ordep/repos/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info


I recently updated it because I believe this problem was related with my nvim version, but just was like a 3 month diff between versions.

**Comment by Pedro-Nicolas-Rios-Vargas** [comment]
Already find the problem, the Neovim update method I used make

**Comment by j-hui** [comment]
No worries, glad you figured it out XD
