### ISSUE TITLE
fidget setup doesn't work

### ISSUE THREAD

**Issue by adorostkar** [j-hui/fidget.nvim#208]
Hello,
I am trying to configure fidget for neovim. I use Lazy
       { 
           'j-hui/fidget.nvim',
           config = function()
               require('fidget').setup()
           end,
       },
       
however after the setup the plugin is not working. I tried  `:lua print(require('fidget').is_installed())` which returns `false`

I tried manually running `:lua require('fidget').setup({})` which also doesn't work since afterwards the call to `is_installed()` is still false

NeoVim version is 0.9.4

There is no log for fidget in .local/share/nvim/

**Comment by adorostkar** [comment]
So that is the reason. I actually tried the legacy branch when I wrote this. Now it throws the exact same message. How should I figure out why this doesn't work though?

**Comment by j-hui** [comment]
Can you please be more specific about what exactly doesn’t work? Is it notifications in general (calling `fidget.notify()` does nothing), or LSP progress messages not showing up (in which case, which LSP server(s) are you using), or is the plugin crashing?

**Comment by adorostkar** [comment]
Maybe I am misunderstanding the usage but for instance when you change the configuration of neo vim, it gives a warning message. This message I assume would be captured and shown by fidget but this doesn't happen. 

I tried fidget.notify() and it works. The plugin doesn't crash and it works with lsp servers. I have `null-ls, bash-language-server`.

The plugin is not crashing.

**Comment by j-hui** [comment]
> when you change the configuration of neo vim, it gives a warning message. This message I assume would be captured and shown by fidget but this doesn't happen.

This sounds like the behavior of Lazy, which calls `vim.notify()` when your Lazy config has changed.

Fidget (and other notification plugins) work by overriding `vim.notify = fidget.notify`; you can let Fidget handle that for you during `setup()` time by setting the `notification.override_vim_notify` option to `true`.

By the way, Lazy seems to assume that whatever notification plugin you're using supports in-buffer Markdown rendering, which Fidget does not. On the other hand, [nvim-notify](https://github.com/rcarriga/nvim-notify) does; so you might want to consider also installing that. Fidget uses [some heuristics](https://github.com/j-hui/fidget.nvim/blob/a3e1e79116ceb93d4c8c0ff432bf506b3213a24d/lua/fidget/notification.lua#L251) to figure out if it should redirect the message to be rendered by nvim-notify.

> I tried fidget.notify() and it works. The plugin doesn't crash and it works with lsp servers. I have `null-ls`, `bash-language-server`.

In that case, it seems like the plugin is working fine. I'm going to close this issue now, but please re-open if you have any more issues.
