### ISSUE TITLE
Fidget not showing LSP related notifications

### ISSUE THREAD

**Issue by OXY2DEV** [j-hui/fidget.nvim#209]
I have installed `fidget.nvim`, but it doesn't show any notifications.

I have,
Used `.setup()`[no options passed] in the `config`.
Checked that `fidget.nvim` is installed.
Sent a notification through `.notify()` which is properly shown.
Checked the supported lsp list and found `tsserver` is supported.

So what am I doing wrong?
Do I need to do something else other than calling `require("fidget").setup()`?

**Comment by j-hui** [comment]
Can you please specify a TS repo + a minimal nvim config where I can reproduce this issue?

Also, what version of Fidget are you on? Can you please make sure you are on the latest version? In particular, you need to make sure that the `progress.ignore_empty_messages` setting is set to `false` (which is the default as of https://github.com/j-hui/fidget.nvim/commit/5aa7cd32c2446fe4a058d6f991c6579c3fdb4c76; [see also](https://github.com/j-hui/fidget.nvim/issues/176#issuecomment-1843230503)).

Another issue, [reported long ago](https://github.com/j-hui/fidget.nvim/issues/17#issuecomment-1023619881), is that tsserver doesn't send progress messages when in a pure JS repo. Please try with a project that contains TS files, or try with another known working language and LSP server.

You should also check Fidget's logs to confirm that the LSP server is actually sending anything. If it's misconfigured and not sending any messages, then there's nothing Fidget can do.

**Comment by OXY2DEV** [comment]
Yep. `tsserver` doesn't send notifications in a pure `JS` repo.

I am getting notifications in a `TS` project.

Thanks for pointing that out.

**Comment by j-hui** [comment]
Awesome, great to hear. By the way, here's a tip from someone that might help you get it working on a JS repo: https://github.com/j-hui/fidget.nvim/issues/17

**Comment by OXY2DEV** [comment]
Thanks for that.

It was just that I thought `fidget.nvim` reads `lsp.log`(output of `:LspLog`) and I was getting a bunch of notifications in the `lsp.log` file(mostly `... initialised`, `... report to upstream. This warning is harmless.`, and a bunch of `json` like objects) and they all had `[INFO]`, `[START]`, `[DEBUG]` Infront of them. So I thought the plugin wasn't working.
![Screenshot_2024-02-03-20-10-11-631_com termux-edit](https://github.com/j-hui/fidget.nvim/assets/122956967/e78384ab-a6b4-4aee-a9f6-a3577344ebdc)

I am very new to LSP in general and only managed to get it working after spending hours tweaking(`lsp-zero` and other such plugins don't seem to work [probably my fault]). So everything is a mess in my config(and everyone's dotfiles for LSP look different so can't use them as reference)

**Comment by OXY2DEV** [comment]
Since you are far more knowledgeable than me, I have a question.

Is there an actual full length guide on setting up `lsp`?

Cause I had to first go to `nvim-lspconfig` git repo. Than I had to go to `nvim-cmp` git-repo. Then I realised every server needs manual installation so I went back to `nvim-lspconfig` and `mason-lspconfig` and then I went to `LuaSnip` git repo to add s snippets.

And then I stumbled in the dark for a few hours before setting everything up.

And I have no clue whether I have set `LSP` up properly or not. So a guide would be very much appreciated.

**Comment by j-hui** [comment]
> It was just that I thought fidget.nvim reads lsp.log(output of :LspLog)

Fidget doesn't do that---it just polls for progress messages LSP servers send to Neovim via the `$/progress` endpoint.

That said, it looks like _something_ is happening and getting set up.

> Is there an actual full length guide on setting up lsp?

Not to my knowledge (at least not one that I followed)... I spent many hours figuring it out myself. I don't use lsp-zero, so I'm not sure how much I can help there. I just directly call the `lspconfig.SERVER.setup()` functions. Supported servers and corresponding configurations can be found [on their server configurations page](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md).

There are definitely a bunch of blog posts folks have written, which you can find by Googling around or searching on the r/neovim subreddit. But some may be out of date, some may be incomplete, some may be misleading.

I will say this: neither Mason nor lspzero are necessary to get LSP working---even lspconfig is technically not necessary (it just bundles a bunch of configuration defaults you can do entirely on your own). I don't use Mason, but I've seen a lot of folks have trouble getting Mason working with Fidget (and it's one of the things I need to look into myself).

> And then I stumbled in the dark for a few hours before setting everything up.

That sucks, I feel for you. But I've just accepted that that's how it is 🙃 just make sure you understand _why_ things work in the end (and ideally, why things don't work!).

> And I have no clue whether I have set LSP up properly or not.

If you're just wondering about LSP: set up a hello world project, pop open neovim, add a stray  keyword (e.g., `for`) in your buffer, and see if you get a complaint from your LSP server. If so, then it's working.

As for progress notifications, make sure to check using a known-working LSP server. I've found `rust-analyzer` to be quite reliable.
