### ISSUE TITLE
Update a required Neovim version to v0.9.0+

### ISSUE THREAD

**Issue by lewart** [j-hui/fidget.nvim#225]
The README.md file currently states that fidget requires Neovim 0.8.0+, but this is incorrect for versions starting from v0.0.0.

When I try to run a fidget v0.0.0 or newer in a Neovim 0.8.3, it fails with error

```
Error executing vim.schedule lua callback: vim/shared.lua:0: plain: expected boolean, got table
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        ...e/nvim/lazy/fidget.nvim/lua/fidget/notification/view.lua:163: in function 'render_item'
```

A gsplit function accepts a table type parameter since Neovim 0.9.0.

Please correct a required version in a READMEmd file to v0.9.0+.

P.S.
It would be useful to see an information about changed required Neovim version in release-notes of fidget v0.0.0.

**Comment by lewart** [comment]
Thank you for your time!

I meant is just editing a release note https://github.com/j-hui/fidget.nvim/releases/tag/v0.0.0.

**Comment by j-hui** [comment]
No problem! It's fixed.

**Comment by lewart** [comment]
Thank You!
Keep up the good work!

**Comment by wookayin** [comment]
Such changes should bump up minor versions, not only the patch versions.
