### ISSUE TITLE
"Could not open Fidget log" when using default options

### ISSUE THREAD

**Issue by Diablo-D3** [j-hui/fidget.nvim#226]
https://github.com/j-hui/fidget.nvim/blob/ebb8e44d6c37337e3b4f9bce31842573fa96bf8d/lua/fidget/logger.lua#L63

Seems to be coming from this.

Either logs should not be generated by default, or the directory (`vim.fn.stdpath("cache")` seems to evaluate to `~/.cache/nvim`) should be created first.

**Comment by j-hui** [comment]
Thanks for filing this issue!

I never caught this because Lazy would always create this directory for me XD: https://github.com/folke/lazy.nvim/blob/83493db50a434a4c5c648faf41e2ead80f96e478/lua/lazy/core/cache.lua#L389

Out of curiosity, what plugin manager are you using (if any)?

**Comment by j-hui** [comment]
lol my trailing comment suggests that I _almost_ got around to creating the directory myself, but forgor what I was doing: https://github.com/j-hui/fidget.nvim/blob/ebb8e44d6c37337e3b4f9bce31842573fa96bf8d/lua/fidget/logger.lua#L58

**Comment by j-hui** [comment]
@Diablo-D3 can you check that this fixed your issue?

**Comment by Diablo-D3** [comment]
Works.
