### ISSUE TITLE
Cannot ignore null-ls

### ISSUE THREAD

**Issue by sinkr** [j-hui/fidget.nvim#232]
I know this has been discussed alot here before, but none of those code snippets/methodologies work.  Following what I think is [outlined here](https://github.com/j-hui/fidget.nvim/issues/75#issuecomment-1881632980) to go into `opts`, I have tried every combination that null/none-ls could be called as to no avail.

Full Lazy plugin config from `.nvim/lua/plugins`
```
return {
  "j-hui/fidget.nvim",
  opts = {
    {
      progress = {
        ignore = { "null-ls", "null_ls", "none-ls", "none_ls" },
      },
    },
  },
}
```
I also have tried this config sans one extra set of braces:
```
return {
  "j-hui/fidget.nvim",
  opts = {
    progress = {
      ignore = { "null-ls", "null_ls", "none-ls", "none_ls" },
    },
  },
}
```
I have also tried calling `setup()` in both config and init functions explicitly to no avail:
```
return {
  "j-hui/fidget.nvim",
  config = function()
    require("fidget").setup()
  end,
  opts = {
    progress = {
      ignore = { "null-ls", "null_ls", "none-ls", "none_ls" },
    },
  },
}
```

**Comment by j-hui** [comment]
I'm not exactly sure how the Lazyvim distribution's plugin configuration system works, but assuming it is the same as the [lazy.nvim plugin spec](https://github.com/folke/lazy.nvim?tab=readme-ov-file#-plugin-spec), the first and third code snippet are wrong. In the first, you are nesting the options table one level deeper than you should be, while in the third, you are specifying an options table but not using it in your `config` function. The second one looks right to me at a glance.

Now, I'm not sure what null-ls uses as its client name, but that should be caught here: https://github.com/j-hui/fidget.nvim/blob/1ba38e4cbb24683973e00c2e36f53ae64da38ef5/lua/fidget/progress.lua#L217-L225

I recommend turning on `INFO`-level [logging](https://github.com/j-hui/fidget.nvim/blob/1ba38e4cbb24683973e00c2e36f53ae64da38ef5/doc/fidget-option.txt#L845-L861) and looking at the [log file](https://github.com/j-hui/fidget.nvim/blob/1ba38e4cbb24683973e00c2e36f53ae64da38ef5/doc/fidget-option.txt#L903) to see what the `lsp_client.name` of those unwanted notifications is, logged here: https://github.com/j-hui/fidget.nvim/blob/1ba38e4cbb24683973e00c2e36f53ae64da38ef5/lua/fidget/progress.lua#L227

**Comment by j-hui** [comment]
@sinkr have you been able to resolve this issue?

**Comment by sinkr** [comment]
No.  I never could get it to work with Noice (i.e. LazyVim), so I just disabled and moved on.

**Comment by j-hui** [comment]
I finally got around to setting up none-ls myself and checking. Just `ignore = { "null-ls" }` should be sufficient (that is the name of the LSP server, which `ignore` uses).

I also pushed a01443a which allows you to specify a per-message filter, in case you need anything more complicated.

I'm closing this issue now since it doesn't seem like there is much more to be done.
