### ISSUE TITLE
Fidget freezes in command line mode

### ISSUE THREAD

**Issue by lopi-py** [j-hui/fidget.nvim#24]
https://gyazo.com/629c72ccc09c2f19d06f6350dc6f806f

**Comment by j-hui** [comment]
I can reproduce (totally hadn't noticed this before), but have no idea why this happens. I don't know when I'll get a chance to get to this, but thank you for bringing it up.

**Comment by lopi-py** [comment]
I'm pretty sure this is a neovim issue, I've seen this "freezing" in other plugins
