### ISSUE TITLE
Fidget background not transparent after setting window = { blend = 0 }

### ISSUE THREAD

**Issue by M0hanrajp** [j-hui/fidget.nvim#240]
**[ Issue Description ]**

Initially I Changed my colorscheme to 'gruvbox' and set transparent_mode as 'true'. [This works]
Since fidget background was opaque with black color I decided to make the following changes:
```lua
      {
        'j-hui/fidget.nvim',
        config = function()
          require('fidget').setup {
            window = {
              blend = 0, -- Background color opacity in the notification window
            },
          }
        end,
      },
```
Even after setting blend = 0 or winblend = 0, the fidget background stays the same.

![Screenshot (23)](https://github.com/j-hui/fidget.nvim/assets/168116222/6c3665bb-434c-432f-834e-4fe8434533bb)

Also there was an error recorded in fidget.nvim.log:
```lua
:~/.cache/nvim$ cat fidget.nvim.log
[WARN  Mon May 20 12:12:35 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:12:35 2024] /lua/fidget.lua:52: - unknown option: window
[WARN  Mon May 20 12:18:23 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:18:23 2024] /lua/fidget.lua:52: - unknown option: window
[WARN  Mon May 20 12:19:07 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:19:07 2024] /lua/fidget.lua:52: - unknown option: window
[WARN  Mon May 20 12:19:23 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:19:23 2024] /lua/fidget.lua:52: - unknown option: window
[WARN  Mon May 20 12:19:52 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:19:52 2024] /lua/fidget.lua:52: - unknown option: window
[WARN  Mon May 20 12:30:43 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:30:43 2024] /lua/fidget.lua:52: - unknown option: window
[WARN  Mon May 20 12:31:13 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:31:13 2024] /lua/fidget.lua:52: - unknown option: window
[WARN  Mon May 20 12:36:40 2024] /lua/fidget.lua:50: Encountered unknown options during setup():
[WARN  Mon May 20 12:36:40 2024] /lua/fidget.lua:52: - unknown option: window
```
---

Please help on this,
Thanks

**Comment by j-hui** [comment]
Per the [documentation](https://github.com/j-hui/fidget.nvim/blob/ef99df04a1c53a453602421bc0f756997edc8289/doc/fidget-option.txt#L687), the option isn't `window.blend` (nor `window.winblend`), it's `notification.window.blend`. So you should be calling `setup()` like this:

```lua
require('fidget').setup {
  notification = { -- NOTE: you're missing this outer table
    window = {
      winblend = 0, -- NOTE: it's winblend, not blend
    },
  },
}
```

So at least it should start doing _something_ for you. But how that option interacts with everyone's colorscheme and terminal transparency settings has been... hard to predict. In my experience. So your mileage may vary.

FWIW there's a longstanding issue #32 that tracks a particular problem I've had, that you may be interested in looking at.

**Comment by M0hanrajp** [comment]
Thankyou @j-hui, it's working!

![Screenshot (24)](https://github.com/j-hui/fidget.nvim/assets/168116222/3991fdee-4884-4ca9-af03-8f226cfacf7a)

**Comment by 9mm** [comment]
I had a side question not really important enough for a whole new issue. Mine currently looks like this

How did you get different colors in your gif in the README? All my text is white, it's not different colors.

I'm also using catpuccin and i have tried enabling the `fidget = true` in integrations, and it just changed text from all gray to all white, but not with syntax highlighting. Are you using some other special config?

<img width="547" alt="image" src="https://github.com/j-hui/fidget.nvim/assets/1386207/a3ed5869-3af0-4614-b4a1-f4ecc888a72c">

**Comment by M0hanrajp** [comment]
> I had a side question not really important enough for a whole new issue. Mine currently looks like this
> 
> How did you get different colors in your gif in the README? All my text is white, it's not different colors.
> 
> I'm also using catpuccin and i have tried enabling the `fidget = true` in integrations, and it just changed text from all gray to all white, but not with syntax highlighting. Are you using some other special config?
> 
> <img alt="image" width="547" src="https://private-user-images.githubusercontent.com/1386207/333891466-a3ed5869-3af0-4614-b4a1-f4ecc888a72c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzgzNzUsIm5iZiI6MTcxNjczODA3NSwicGF0aCI6Ii8xMzg2MjA3LzMzMzg5MTQ2Ni1hM2VkNTg2OS0zYWYwLTQ2MTQtYjRhMS1mNGVjYzg4OGE3MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMTU0MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRhN2Q1YzVhYjYwZGJmNDM2MWRjNzMwYTNmNTRiOTUxMDBlNDYyMTI1Yjk4ZTZmMWEyYjkzNjQ0OTA1ZWM3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TGWUokQ9JBXIodQQdp6oVYsMqVMVySa05UOcHKe1JUE">

---
Hello @j-hui , can you please advice @9mm ?
Thanks.
