### ISSUE TITLE
get_active_clients is deprecated in nvim 0.10

### ISSUE THREAD

**Issue by seocamo** [j-hui/fidget.nvim#242]
replace vim.lsp.get_active_clients with (vim.lsp.get_clients or vim.lsp.get_active_clients) as the new function in 0.10 is vim.lsp.get_clients.

this will make it work on old versions too.

get_active_clients is removed in 0.12

**Comment by j-hui** [comment]
Can you please specify where exactly in Fidget you are seeing this issue?

**Comment by seocamo** [comment]
line 490  `for _, client in ipairs(vim.lsp.get_active_clients()) do`  in fidget.lua

**Comment by j-hui** [comment]
Are you talking about line 492 in `fidget.lua` from the deprecated `legacy` branch?

https://github.com/j-hui/fidget.nvim/blob/2f7c08f45639a64a5c0abcf67321d52c3f499ae6/lua/fidget.lua#L492

I'm not going to update that. I highly recommend switching to a more recent version of Fidget.

**Comment by seocamo** [comment]
yes sorry, no one else ask to other branch, so i didn't see i was on that :)
