### ISSUE TITLE
Add Elixir LS to "Known compatible LSP servers" wiki page

### ISSUE THREAD

**Issue by fuelen** [j-hui/fidget.nvim#243]
Please include the following LS for Elixir
* https://github.com/elixir-tools/next-ls
* https://github.com/lexical-lsp/lexical

both servers support progress

**Comment by j-hui** [comment]
Thanks for bringing this up! I just added next and lexical to the page.

The name of your issue says "Elixir LS"---is that referring to [elixirls](https://github.com/elixir-lsp/elixir-ls) specifically as well or just the two other Elixir servers you mentioned? (As far as I'm aware, elixirls still doesn't support LSP progress, according to [this issue](https://github.com/elixir-lsp/elixir-ls/issues/848))

**Comment by fuelen** [comment]
By using "Elixir LS" I just wanted to say "Elixir language servers" :slightly_smiling_face: No referring to elixirls. Sorry for the confusion.
And thank you for updating the wiki
