### ISSUE TITLE
Can i suppress `diagnosing` message?

### ISSUE THREAD

**Issue by Jaehaks** [j-hui/fidget.nvim#249]
Thank you for your efforts, 

I want to see only lsp loading messages, but recently fidget shows additional messages about diagnosing.
I cannot find the options which can do this. Is there any way to suppress them?

![image](https://github.com/j-hui/fidget.nvim/assets/26200835/8bf5814e-8c54-4adb-90bb-b4be9cae9351)

**Comment by j-hui** [comment]
The "Diagnosing" message is specific to an LSP server (in this case, `lua_ls`).

I just pushed a feature that supports filtering on a per-message basis. You should be able remove those messages with something like:

```lua
progress.ignore = { -- NOTE: this is short-hand, not the actual syntax for specifying a nested table
  function(msg)
    return msg.lsp_client.name == "lua_ls" and string.find(msg.title, "Diagnosing")
  end,
}
```

**Comment by Jaehaks** [comment]
@j-hui 
It is solved, Thanks
