### ISSUE TITLE
Commit 600ecc1 broke my fidget.nvim

### ISSUE THREAD

**Issue by AnderCabrera** [j-hui/fidget.nvim#253]
Well, I was going to use my nvim as always and I updated my packages (I'm using Lazy). 
So, after the update, my fidget.nvim doesn't work; it shows an error message.
![image](https://github.com/user-attachments/assets/27cb9812-6e1a-4b11-84c7-8b85dd74c007)

I entered the fidget.nvim folder and did a `git checkout` c12f8a5, and it worked again.
![image](https://github.com/user-attachments/assets/65f3e154-00b6-4f1a-bba3-2b2ec14c15e4)

What could be the problem? Or is it something related to my configs?

**Comment by xiyuzhai** [comment]
1.4.4 works for me, but 1.4.5 gives  me the same errors as you.

**Comment by j-hui** [comment]
Thanks for reporting this. Just checking, what version of Neovim are you all using?

**Comment by sentientmachin3** [comment]
Hi, I have the same issue, I'm using version 0.9.5.

**Comment by j-hui** [comment]
Sorry about this all, this came from #252. I should have tested this with different Neovim versions before merging.

Please update again, it should be fixed now! Feel free to reopen this issue if errors persist.

**Comment by sentientmachin3** [comment]
Fixed on my side thanks!
