### ISSUE TITLE
Progress never completes

### ISSUE THREAD

**Issue by j-hui** [j-hui/fidget.nvim#28]
Follow-up from #19 ; this issue also appears to be relevant for other language servers (e.g., angularls; see #26 ).

If a language server never sends an `end` notification, the fidget will stay on screen indefinitely. This seems to be language server-specific:

- gopls: #19,  https://github.com/golang/go/issues/50885
- angularls: #26 

I'm not sure what the best way to handle this is. In particular, I'm skeptical that this is a valid interpretation of the LSP spec. Possible workarounds for particular cases include:

- implementing some kind of timeout mechanism (suggested by gopls maintainers). 
- killing the task if the `kind` field is `nil` (suggested in #26).

**Comment by wookayin** [comment]
As a workaround, we may add some commands like `:FidgetClose` ?
