### ISSUE TITLE
[Config] text.done seems to trim the icon

### ISSUE THREAD

**Issue by lopi-py** [j-hui/fidget.nvim#3]
![image](https://user-images.githubusercontent.com/70210066/151074569-39fa630e-eb93-4bbd-800d-d7e11db18283.png)
fidget is trimming the right side of the icon, seems to only render the first character of `text.done`
## Config
```lua
require("fidget").setup({
    text = {
        spinner = "arc",
        done = require("icons").check,
    },
})
```
**icons.lua**
![image](https://user-images.githubusercontent.com/70210066/151074872-08a86e07-9a73-4f36-8ce1-9bce5b888452.png)

**Comment by j-hui** [comment]
I'm unable to reproduce this problem using ASCII text. I see all characters rendered using `done = "DONE"`:

![image](https://user-images.githubusercontent.com/11800204/151083072-2d1be473-a298-4396-bf94-12f9bb45f857.png)

I suspect that this is either an issue with Unicode, or with your font/terminal (I've encountered similar issues in the past where icons appear cut off). Can you paste the icon in this issue? What font/terminal emulator are you using?

**Comment by Lopi-py** [comment]
> Can you paste the icon in this issue? What font/terminal emulator are you using?
* **Icon**: " "
* **Font**: MesloLGS NF(nerd font)
* **Terminal**: Windows Terminal(cmd.exe profile)

**Comment by Lopi-py** [comment]
![image](https://user-images.githubusercontent.com/70210066/151084754-50f1f633-0d45-4438-8422-00946a5fb2e8.png)
it works with letters, but if I put an icon, just takes the first character

**Comment by j-hui** [comment]
I'm unable to reproduce this error (on Alacritty running on NixOS with a completely different font):

![image](https://user-images.githubusercontent.com/11800204/151087064-d63294ad-bc44-4410-89c5-3473f890185e.png)

I'm sorry but I'm not sure I can be of much help here.

That being said, there's definitely something fishy happening with that icon. I don't seem to be able to render it properly in my config:
![image](https://user-images.githubusercontent.com/11800204/151087151-35a20788-4d4b-4e4c-8c3e-674d1bc36164.png)

Sorry this isn't ideal. Hopefully someone else will pick this up.. in the meantime, does the original check mark icon work for you?

**Comment by Lopi-py** [comment]
Yes, the original check mark works

**Comment by Lopi-py** [comment]
#23 fixed this but only if `window.blend` is set to 0

**Comment by j-hui** [comment]
That's really odd. There's something very fishy going on with how background highlights are working; disabling `winblend` seems to be a workaround but I'll have to investigate more.

**Comment by Iskustvo** [comment]
Hi @lopi-py,

I'm pretty sure that the issue you described has nothing to do with this plugin, nor Neovim in general.
It's most likely issue with font or the terminal which you are using.
I have the same issue and so far I was avoiding it by adding one space after each icon, but when you need to interactively go over it (like in [trouble.nvim](https://github.com/folke/trouble.nvim)) this really falls apart quickly :smile: 

Don't know which terminal you are using, but I'm on [st](https://st.suckless.org/) and I can tell you that it doesn't work for me, while [alacritty](https://alacritty.org/index.html) does.
Luckily, I found [opened PR](https://github.com/LukeSmithxyz/st/pull/349) regarding the patch which claims to fix it, so we might get it truly fixed for `st` as well.
