### ISSUE TITLE
Details get folded according to foldlevel.

### ISSUE THREAD

**Issue by fky2015** [j-hui/fidget.nvim#31]
Set `foldlevel=99` before opening a file will also fold the detail of LSP progress.

[![asciicast](https://asciinema.org/a/GIRRKmkUFM3XX48COcF5nlNtK.svg)](https://asciinema.org/a/GIRRKmkUFM3XX48COcF5nlNtK)

Is there any way to prevent that happen without changing the buffer's `foldlevel`?

**Comment by fky2015** [comment]
Sorry for the delayed response. #37 does not help with the issue.

FYI, I only set `foldmethod=expr` and `foldexpr=nvim_treesitter#foldexpr()` according to the [docs here](https://github.com/nvim-treesitter/nvim-treesitter#folding). These are the settings that will automatically enable folding in a **window**.

> Tree-sitter based folding. (Technically not a module because it's per windows and not per buffer.)

That seems to be the key problem related to this issue, but I cannot figure a way out to solve that.

**Comment by fky2015** [comment]
Pretty weird, I can not reproduce this issue with the latest code today. Everything is back to normal.

Thanks for your help!

**Comment by j-hui** [comment]
That's weird, but I'm glad that it fixed itself! Let me know if this issue pops up again.

**Comment by Integralist** [comment]
👋🏻 

I'm having this issue at the moment 😬 

For other tools I've used...

```
vim.api.nvim_create_autocmd("FileType", {
    pattern = "TelescopeResults",
    command = "setlocal nofoldenable"
})
```

But I'm not sure what that looks like for fidget?

**Comment by Integralist** [comment]
<img width="292" alt="Screenshot 2024-01-05 at 13 57 53" src="https://github.com/j-hui/fidget.nvim/assets/180050/964f067c-b874-415d-9d54-e8e376b7dfbd">

**Comment by j-hui** [comment]
@Integralist Can you please provide more details on what your global fold settings are?

Also, if you're able to, please try the following change:

```diff
diff --git i/lua/fidget/notification/window.lua w/lua/fidget/notification/window.lua
index 3d8d7b1..12b29ea 100644
--- i/lua/fidget/notification/window.lua
+++ w/lua/fidget/notification/window.lua
@@ -381,6 +381,7 @@ function M.get_window(row, col, anchor, width, height)
   M.win_set_local_options(state.window_id, {
     winblend = M.options.winblend, -- Transparent background
     winhighlight = winhighlight ~= "" and winhighlight or nil,
+    foldenable = false,
   })
   return state.window_id
 end
```

And let me know if that fixes your issue. It's basically the (unhelpful) fix attempted in #37, but ported to the current version. If it does fix your issue, I'll commit it to `main`.

For what it's worth, the `filetype` of the Fidget buffer is just `fidget`, so you can also set up an autocmd for the notification buffer like you did for Telescope. But that's not an ideal solution IMO and I'd like to fix your issue without resorting to autocmds like that.

**Comment by Integralist** [comment]
Thanks. I appreciate you taking the time to provide different options to resolve this. I've actually disabled folds completely now as I just found they hindered me more than helped me. So for me this is no longer an issue. Thanks again for your time.

**Comment by aemonge** [comment]
This is not working, but should it?
```
    notification = {
        filter = vim.log.levels.INFO,
        -- filter = vim.log.levels.WARN,
        override_vim_notify = true,
        window = {
            render_limit = 3,
            normal_hl = "NormalFloat",
            winblend = 0,
            zindex = 45,
            foldenable = false,
        },
    },
```
