### ISSUE TITLE
Highlights differ if window spans area with text

### ISSUE THREAD

**Issue by gegoune** [j-hui/fidget.nvim#32]
Hey, I was noticing that sometimes I get dimmed notifications and finally caught the scenario when dimming happens.

Highlights will be dimmed if fidget's window is drawn over area with no text; that is not the case if there is text on lines underneath fidget's window.

Please see this quick screencast illustrating above:

https://user-images.githubusercontent.com/69750637/151766646-ba4a849b-12cb-485a-93ba-ff6362242e7c.mov

Please note that dimming goes away even if I change buffer while previously dimmed text still persist on the screen, but underlying lines are filed with text.

Desired highlights are the brighter ones:
<img width="286" alt="title" src="https://user-images.githubusercontent.com/69750637/151767125-c87f236a-3687-4f75-b212-7a5eb2f51ceb.png">
<img width="274" alt="task" src="https://user-images.githubusercontent.com/69750637/151767129-00a0facb-178c-4f54-88a0-726c62426804.png">

Tried with:
```lua
require('fidget').setup {
  window = {
    winblend = 100,
  },
}
```
as well as `window.winblend = 0` - outcome is the same in both cases.

**Comment by xulongwu4** [comment]
I noticed that this doesn't happen when `winblend` is zero

**Comment by gegoune** [comment]
Can confirm. As you can see in my original report I mistakenly set `window.winblend` instead of `window.blend` which I believe was in readme/docs at the time.

**Comment by j-hui** [comment]
Yeah there was previously a typo in the docs, which has since been fixed.

Sorry I haven't had time to look into this, but ideally this shouldn't happen even with `window.blend` set to 100.

**Comment by lalitmee** [comment]
@j-hui, I am not sure if this is the related issue, but I am also facing something like this.

![fidget](https://user-images.githubusercontent.com/10762218/156866332-a14f6cb4-25fb-4210-9911-2c8984a7fa3c.gif)

I have tried setting the highlights but that is only setting the highlight for the foreground, not the background.

**Comment by lalitmee** [comment]
In my config, I had `Normal` highlight `guibg` set to `NONE`. 

Removed that and fixed.

**Comment by j-hui** [comment]
Seems to be fixable with some amount of config wrangling.

**Comment by gegoune** [comment]
Would you mind explaining what you have in mind? I am still seeing that issue with latest changes (great work btw! Thanks a bunch!)

**Comment by j-hui** [comment]
@gegoune Sure, what config and theme are you using at the moment?

**Comment by gegoune** [comment]
All defaults from fight.nvim, just calling `setup()`, colorscheme is [zenbones](https://github.com/mcchrish/zenbones.nvim).

**Comment by j-hui** [comment]
Ugh ok I had really not closely read the steps to reproduce from the original post, this is clearly still an issue.

**Comment by rtgiskard** [comment]
> Ugh ok I had really not closely read the steps to reproduce from the original post, this is clearly still an issue.

I have just find the similar issue related to `winblend`:
![winblend issue](https://github.com/j-hui/fidget.nvim/assets/34635040/7c607b01-48b9-45b3-82d9-2115ef0077f4)

The C source file end at line 37, the right bottom notifications are fidget progress messages from `<C-f>` format operation.
The color of popup progress message greatly inflected by the background context with `winblend=100`.

To reproduce, you may use [this config](https://github.com/rtgiskard/lazyNvim), and edit some file like `lua`

**Comment by j-hui** [comment]
Yeah so this is something to do with the semantics of winblend. I looked into it at one point since re-opening this issue, but didn’t really conclude anything useful, though I suspect a fix will either have to come from (1) Neovim itself, or (2) switching to extmark-based rendering (which gives me more fine-grained control over which parts of the buffer are populated).

I wanted to wait until I’d experimented with (2) first before filing an issue upstream/haven’t had bandwidth to get around to it (I’m working on deduplication rn)

**Comment by baggiponte** [comment]
I had the same problem as @lalitmee. I am using [gruvbox material with transparent background](https://github.com/baggiponte/dotfiles/blob/2db69a7a32610111bc1c14afa47a8f9ff3086b57/nvim/lua/baggiponte/plugins/ui/colorscheme.lua#L19) and I solved it by setting winblend to 0.
