### ISSUE TITLE
Useability of spinners as UI elements in other plugins

### ISSUE THREAD

**Issue by hbiel** [j-hui/fidget.nvim#47]
I've wondered if the available spinners could be used independent of the lsp functionalities.

Is there any way to get an 'instance' of an spinner so it can be used in other UI elements?

**Comment by j-hui** [comment]
They certainly can, with some amount of refactoring on my part. 

I've thought about eventually breaking up fidget into smaller, more reusable components: the fidget buffer, the progress handler that populates it, and the floating window that displays it. But I'm not sure exactly what the interface between the three should be. 

For your case, where were you thinking of using the spinner?

**Comment by hbiel** [comment]
I was thinking of using it in the telescope prompt until the search is finished. There's a hook that can be overwritten via user configuration (see https://github.com/nvim-telescope/telescope.nvim/issues/1713).

But I don't know if this would be even possible without adjustments in telescope.

**Comment by j-hui** [comment]
Oh are you talking about just the spinner animation, without all the LSP-specific stuff?

I adapted all of Fidget's [spinners](https://github.com/j-hui/fidget.nvim/blob/main/lua/fidget/spinners.lua) from the [cli-spinners](https://github.com/sindresorhus/cli-spinners) npm packatge. If you want to use any of those anywhere else, you can just `require"fidget.spinners"` and select the animation you like. But it will leave it up to the user to figure out how to animate the spinner frames.

In terms of Telescope progress spinner support, it seems like it's being worked on in https://github.com/nvim-telescope/telescope.nvim/pull/1746
