### ISSUE TITLE
Weird window behaviour

### ISSUE THREAD

**Issue by Lopi-py** [j-hui/fidget.nvim#5]
https://gyazo.com/c8d1cdd0c0c9dff66f583b448c8d3697
When I open NvimTree the floating progress does not keep in the window and goes to NvimTree window.

**Comment by j-hui** [comment]
Thanks for bringing this up. I've noticed that this also happens with Telescope windows.

As you've probably surmised, right now I just align the fidget window with whatever the foreground window is, which doesn't always correspond to the file being processed by the LSP server.

I'm not sure there's a reliable way to always figure out what the right window should be, but I'll look into it.
