### ISSUE TITLE
[Bug]: interaction floating window of nvim-bqf

### ISSUE THREAD

**Issue by akinsho** [j-hui/fidget.nvim#53]
Hi 👋🏿 ,

Thanks for your work on this plugin, It's really great.

I recently just realised that when using the [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) which opens a floating window preview for quickfix entries the win blend is set to `100` making the content illegible

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/22454918/154953341-1044144e-167c-4693-868a-2cdaf168ab3f.png">

I narrowed this issue down to an interaction with this plugin. I'm not sure how or why, but the figdet seems to cause the window blend for the floating window from that plugin to be set to 100. On tweaking this plugin so that the window blend is 0 it works fine. I think that maybe the fidget is being attached to floating window for this plugin rather than being fixed to the window that it was associated with where the lsp was being loaded

**Comment by j-hui** [comment]
Perhaps related to #32 ?

Then again, I have no idea why Fidget would clash with bqf's floating preview.. Fidget only ever sets winblend for windows it creates.

In any case, this is yet another one of those cases where Fidget would be better off if with some setting to blacklist certain buffers and windows. Do you know if there's any kind of clue plugins can use to determine whether they are in bqf's preview window?

**Comment by akinsho** [comment]
@j-hui it could be related, although didn't really understand that issue entirely. Re. detecting bqf's window, I guess you could as a general rule check if the window that the fidget is inside is a float and if it is then don't attach to it. e.g.
using `win_gettype` which should return `popup` if fidget is indeed applying settings to a popup

**Comment by akinsho** [comment]
So I hit this issue again with another plugin and the author managed to track it down to an issue in neovim core but with a workaround suggested in the thread https://github.com/b0o/incline.nvim/issues/4#issuecomment-1114777698
essentially, I think this plugin probably sets the winblend using `vim.opt` somehow, which is currently buggy when setting window options. The fix is essentially to create a wrapper function that call `setlocal` via `vim.cmd` instead for now.

**Comment by j-hui** [comment]
Wow, thanks for catching this @akinsho ! We'll probably have to keep in your workaround until the issue in Neovim is fixed in a stable release.
