### ISSUE TITLE
Custom highlights don't work

### ISSUE THREAD

**Issue by FollieHiyuki** [j-hui/fidget.nvim#6]
The highlights are defined inside the `setup()` function with command `highlight!` so my custom highlights won't work if I define them earlier (I'm lazy loading `fidget.nvim`). With this diff I can work around the problem:
```diff
diff --git a/lua/fidget.lua b/lua/fidget.lua
index cdd20a7..5dc5ea7 100644
--- a/lua/fidget.lua
+++ b/lua/fidget.lua
@@ -246,8 +246,12 @@ function M.setup(opts)
     options.text.spinner = spinner
   end
   vim.lsp.handlers["$/progress"] = handle_progress
-  vim.cmd([[highlight! default link FidgetTitle Title]])
-  vim.cmd([[highlight! default link FidgetTask NonText]])
+  if vim.fn.hlexists('FidgetTitle') ~= 1 then
+    vim.cmd [[highlight default link FidgetTitle Title]]
+  end
+  if vim.fn.hlexists('FidgetTask') ~= 1 then
+    vim.cmd [[highlight default link FidgetTask NonText]]
+  end
 end

 return M
```

But there is also a problem with `winhighlight` that makes the text color dimmed or brighter. Here are the screenshots for the same settings on different buffers:

![screenshot1](https://user-images.githubusercontent.com/67634026/151115843-26604a2e-8e46-4759-a3ff-7cf8a199499b.png)

![screenshot2](https://user-images.githubusercontent.com/67634026/151115912-fc623bbf-3900-450a-a87f-9b0e083f6ba9.png)

The colors in used here are #b48ead (for FidgetTitle) and #d8dee9 (for FidgetTask) and I'm using Neovim v0.6.1 in Alpine Linux.

**Comment by j-hui** [comment]
Ok so I think there's actually two things going on here, both related to the kind of confusing way highlights in Vim work.

First of all, I shouldn't have used `highlight!`, which effectively elevates the precedence of `default link` and forces the link. I fixed that in a5039a5.

```vim
hi default link Foo Comment
" hi Foo -> Comment
hi Foo guifg=blue
" hi Foo := guifg=blue
hi default link Foo Comment
" hi Foo := guifg=blue
```

What adds another layer of confusion here is that when you set your colorscheme, any _non-default_ highlights will disappear, and it will revert to the default highlight. I suspect what's going on is that your highlights were cleared during a colorscheme switch at some point.

You may want to wrap them in an autocmd:

```vim
augroup fidget-highlights
  autocmd!
  autocmd ColorScheme * highlight FidgetTitle guifg=#b48ead
  autocmd ColorScheme * highlight FidgetTask guifg=#d8dee9
augroup END
```

(Alternatively, put both highlight statements in a function and call that from the autocmd.)

Does that work for you? If so, I can add this to the documentation.

**Comment by FollieHiyuki** [comment]
I use my own colorscheme though (which is part of my config) and it is loaded with `:colorscheme myscheme`. I do have a 'hi clear' command before defining my own highlights, but it shouldn't interfere (as long as I explicitly define them in the colorscheme).

I pulled the latest commit, and can define the highlights now. The result appears the same as the screenshots from my previous message (the screenshots above was after I applied my diff).

I guess for some reason the window highlight is disrupting the defined highlights, which makes the colors look dimmed or bright randomly.

Should I open another issue for this problem? Probably related to #11 as you pointed. What do you think?

**Comment by j-hui** [comment]
Yeah the flaky winhighlights seem to be a different issue. Let's move the discussion to #11 and close this one. We can always revisit this issue or open a new one if #11 turns to be yet a different problem.
