### ISSUE TITLE
Use vim-notify as a backend

### ISSUE THREAD

**Issue by j-hui** [j-hui/fidget.nvim#62]
The [vim-notify wiki](https://github.com/rcarriga/nvim-notify/wiki/Usage-Recipes#progress-updates) has a recipe for displaying LSP progress updates using their notifications. It looks really sweet!

I haven't had a chance to try out vim-notify yet, but it would be really cool to opt into using that to display progress messages.

**Comment by gegoune** [comment]
I have an opposite suggestion. How about adding functionality of displaying `vim.notify` messages through fidget.nvim? I would really appreciate unified interface and am loving simplicity and unintrusiveness of your plugin.

**Comment by j-hui** [comment]
@gegoune perhaps I can spin off the notification component of fidget as a dedicated notification backend?

(Or it might be even easier to make a PR into vim-notify to use a fidget-like style)

**Comment by gegoune** [comment]
How difficult would it be to implement support here? This approach would require one fewer plugin to be installed. :)

**Comment by pwntester** [comment]
Plus one, it would be great to have fidget as a `vim.notify` backend

**Comment by gregorias** [comment]
The unobtrusive interface is really neat. Plus one to refactoring out the UI component into its own reusable plugin.

**Comment by j-hui** [comment]
I’m sorry to have put this off for so long! I promise I’ll get to it

**Comment by j-hui** [comment]
This should now be possible as of #143. I'm not sure I want to support this kind of thing first-class (despite using nvim-notify myself), but it can now certainly be done with a little hacking (without modifying the plugin) and redirecting the `ProgressMessage` packets toward `nvim-notify` rather than Fidget's own notification backend.

**Comment by j-hui** [comment]
I was originally envisioning using `nvim-notify` for actually displaying the notifications, but I realize now that what I had in mind doesn't make that much sense considering that Fidget's progress subsystem contains a number of Fidget-specific configuration options.

In any case, Fidget is now its own `vim.notify` backend, and [91eb16f](https://github.com/j-hui/fidget.nvim/commit/91eb16fe08d92c742b0aff3ef0d72a7c37e89a6d) provides a way to use `nvim-notify` for notifications that that need features Fidget does not support. With that, I'll close this issue. If anyone would like to suggest any specific `nvim-notify` integrations, please file a new Issue.
