### ISSUE TITLE
Sometimes the fidget window gets closed and there's no way to reopen it

### ISSUE THREAD

**Issue by mrjones2014** [j-hui/fidget.nvim#66]
Sometimes, not exactly sure what causes it, but it seems to have something to do with switching between windows, particularly when you have different filetypes open in each, the fidget window gets closed, and there's a `:FidgetClose` command but no way to manually _open_ the fidget window.

**Comment by j-hui** [comment]
Fidget messages is in some sense ephemeral: once a message is received, a best-effort is made to display it, and if it cannot be displayed in a timely manner, then it won't ever be displayed. The fidget message window is opened only to display messages (i.e., a push schema), and so it doesn't really make sense to open it if it isn't already open. If you're not seeing anything in the window, then chances are the language server had already completed a task and stopped sending notifications.

Perhaps there's a better way to manage notifications, but I'm not sure. Can you give more details about what messages you expected to see, but didn't?

**Comment by mrjones2014** [comment]
Sometimes when rust-analyzer is loading, if I’m switching around windows while waiting for it, if I switch back to the rust window, the fidget window is gone but rust-analyzer still hasn’t finished. I’d expect to still see the progress messages that I think are still being sent by the server (usually it shows that its indexing through a bunch of crates, and the crate names its currently indexing update in the fidget window).

**Comment by j-hui** [comment]
This should be fixed by #143. Please open a new issue if anything similar happens.
