### ISSUE TITLE
Feature Request: Diagnostic issues widget

### ISSUE THREAD

**Issue by mystilleef** [j-hui/fidget.nvim#7]
Is it possible to provide a widget that shows when a buffer, project, or workspace has diagnostic issues?

**Comment by j-hui** [comment]
I may consider adding this once this plugin is more stable, but I consider it a lower priority since this is already handled quite well out of the box by other plugins such as [lualine](https://github.com/nvim-lualine/lualine.nvim) and [bufferline.nvim](https://github.com/akinsho/bufferline.nvim).

**Comment by mystilleef** [comment]
Fair enough. I hide my status and buffer bars by default. That's why `fidget` comes in so handy and has replaced `lspstatus` for me. But I understand my use case might be unique.

**Comment by mystilleef** [comment]
`b0o/incline.nvim` satisfies this issue.

For more info, see

https://github.com/b0o/incline.nvim/issues/26#issuecomment-1231954953

Closing this issue.
