### ISSUE TITLE
Use as a library / low-level API?

### ISSUE THREAD

**Issue by fsouza** [j-hui/fidget.nvim#70]
Thank you for putting this project together, it's really cool. I was wondering if it you'd be open to exposing some functions to allow usage as a library. Could even be as low-level as exposing the fidget itself. Something like:

```lua
local fidget = require('fidget')
local f = fidget.new_fidget(identifier, name)

```

I realize that making those lower level pieces of the API public would increase the potential maintenance burden, but it could be useful for reporting progress on things that aren't LSP. Let me know if this is something you'd be open to and I can definitely prepare a PR!

**Comment by j-hui** [comment]
I have a big rewrite in the works. Stay tuned! (:

**Comment by j-hui** [comment]
By God, more than a year of inactivity on this. Thanks for your patience! See #131
