### ISSUE TITLE
Null ls

### ISSUE THREAD

**Issue by bryant-the-coder** [j-hui/fidget.nvim#75]
How to prevent fidget.nvim from appearing when format on save is setup?

**Comment by bryant-the-coder** [comment]
Are there any highlights that are linked to fidget.nvim? I have set my neovim transparent. But the bg for fidget is a bit ugly :(

**Comment by j-hui** [comment]
There are `FidgetTitle` and `FidgetTask`, but those are primarily for setting the text highlights. 

You might want to try playing with the winblend settings: https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.md#windowblend

**Comment by bryant-the-coder** [comment]
![image](https://user-images.githubusercontent.com/92417638/166108147-c5652340-f96e-4c4a-94d8-bbe87e4b6994.png)
is this normal?

**Comment by j-hui** [comment]
@bryant-the-coder  sorry for the delay. But that doesn't look like a Fidget window?

Another user identified a problem where window local settings were "bleeding" into other windows due to a bug in Neovim (#53), and created a workaround that I just merged in (#77). Can you update Fidget and see if you still have that issue?

**Comment by nshen** [comment]
hi @bryant-the-coder I figure out your problem, the right Lua table syntax with string key is  

```lua
  sources = {
    ["null-ls"] = {
      ignore = true,
    },
  },
```

**Comment by halshar** [comment]
sorry to open this again, but on the new version how do I disable null-ls entirely
the below option does not work
```lua
return {
  "j-hui/fidget.nvim",
  tag = "v1.0.0",
  config = function()
    require("fidget").setup({
      sources = {
        ["null-ls"] = {
          ignore = true,
        },
      },
    })
  end,
}

```

**Comment by j-hui** [comment]
@halshar

```lua
{ -- options table
  progress = {
    ignore = { "null-ls" },
  },
}
```

For more details, please refer to the [options documentation in the README.md](https://github.com/j-hui/fidget.nvim?tab=readme-ov-file#options), and open a new issue if you any further questions.
