### ISSUE TITLE
Fidget makes neovim unusable when diagnostic errors are present

### ISSUE THREAD

**Issue by mystilleef** [j-hui/fidget.nvim#8]
If diagnostic issues are present, I get error messages when I try to do any `vim` motion commands.

This video shows the issue.

https://user-images.githubusercontent.com/273399/151125469-018d4b47-95ab-4306-b1db-a0579208eef3.mp4

**Comment by mystilleef** [comment]
Okay, this seems to be an issue with `null-ls`. I can't reproduce this when `null-ls` is not running.

**Comment by mrjones2014** [comment]
Same issue here. In my recording, I'm just pressing `x` to delete the comma, then a keybind for `:wa` (my formatter brings the comma back so don't worry about that).

![CleanShot-2022-01-26-at-06 48 09](https://user-images.githubusercontent.com/8648891/151158105-daab8c22-f094-4db7-b375-f5fecb99c9d0.gif)

**Comment by mystilleef** [comment]
This `null-ls` commit, https://github.com/jose-elias-alvarez/null-ls.nvim/pull/619, fixes this issue for me.

**Comment by mystilleef** [comment]
I'm closing this issue. Update `null-ls` for the fix.
