### ISSUE TITLE
Winbar compatibility

### ISSUE THREAD

**Issue by zootedb0t** [j-hui/fidget.nvim#81]
After enabling winbar. Fidget spinner appears on the statusline.
![Screenshot (5)](https://user-images.githubusercontent.com/62596687/169156552-9a5e7a28-84f3-41f8-9762-f10edcbcd11e.png)

**Comment by wookayin** [comment]
+1. I think fidget should lift up the position by one row when `winbar` is set.

**Comment by wookayin** [comment]
I've submitted a PR #82 that would add winbar support.
