### ISSUE TITLE
Doesn't work with nvm node js

### ISSUE THREAD

**Issue by timsofteng** [j-hui/fidget.nvim#83]
Hello.
Looks like this plugin doesn't work with `nvm` nodejs.
I'm not 100% sure but it works if node is installed as global package.

**Comment by j-hui** [comment]
I'm not sure that this is Fidget's issue; this plugin just relies on the LSP client being set up by something like nvim-lspconfig.

What language server are you using? And are you able to get any LSP at all (e.g., completion, hover, goto-definition, etc.)?

**Comment by timsofteng** [comment]
@j-hui Sure.
Lsp works.
I use `typescript-language-server` which is installed with `nvm`'s nodejs.

**Comment by j-hui** [comment]
Closed due to inactivity.
