### ISSUE TITLE
Should I expect to see tsserver startup progress?

### ISSUE THREAD

**Issue by tomspeak** [j-hui/fidget.nvim#87]
hey,

the plugin was working for `null-ls` but as I am only using it for formatting I disabled `null-ls` source.

what I want to use this plugin for is to see how long I have to wait until my autocomplete in typescript will start working.

for some reason I do not get any fidget notifications when I start neovim and open a typescript file.

I am opening a file in a directory that has a `tsconfig.json`, and all LSP features are working as expected, I just don't see a loader while it is booting and wanted to know if that is/is not expected.

cheers!

**Comment by tomspeak** [comment]
I do not know if it's relevant, but two things

1. I am using neovim 0.8
2. Even when I enable `null-ls` and see the fidget progress spinner when my formatter runs, `:lua print(require"fidget".is_installed())` returns `false`, no matter what.

**Comment by tomspeak** [comment]
My `typescript-language-server` was out of date, `npm -g install typescript-language-server` fixed it, it is now showing fidget progress correctly.

**Comment by sarmong** [comment]
What version fixed it? It's not working for me in 2.1.0

**Comment by polyzen** [comment]
I don't think I ever got startup progress with typescript-ls, also currently on 2.1.0. Started using https://github.com/jose-elias-alvarez/typescript.nvim at some point which perhaps has to do with it.
