### ISSUE TITLE
E322: line number out of range

### ISSUE THREAD

**Issue by rockyzhang24** [j-hui/fidget.nvim#89]
Sometimes after I quit neovim during fidget running, I get this error in the terminal. I attached a screenshot below.

nvim version: built from master
os: macOS: 12.4

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/11582667/174405611-a70c2007-431b-4732-b918-c3934feee72c.png">

Thank you.

**Comment by oeyoews** [comment]
only in nightly version, this error occur sometimes

**Comment by wonbyte** [comment]
Same issue on:
nvim: `0.7.2`
macOS: `12.15.1`

**Comment by j-hui** [comment]
Closing this in favor of #86
