### ISSUE TITLE
Incompatibilities with null-ls

### ISSUE THREAD

**Issue by Gelio** [j-hui/fidget.nvim#9]
Hey! Very cool plugin, I must say. I started using it and immediately noticed a few weird behaviors involving null-ls

First, when pressing `o` when filling in the commit message in vim-fugitive, I am struck with

![image](https://user-images.githubusercontent.com/889383/151125265-0d8854cc-ffae-48a1-be91-c1240fc6f389.png)

This message appears each time I press `o` or `O` in that buffer for typing in the commit message.

fidget.nvim shows a new task from null-ls each time I hit `o`/`O` and get that error

![image](https://user-images.githubusercontent.com/889383/151125446-bd2f2c67-03c4-40f8-9977-6909f05ad594.png)

It constantly says that the tasks are starting, they never complete.

I have also reproduced that problem in a regular buffer. Pressing `o<Esc>o<Esc>o<Esc>` seems to trigger it and then each time I hit `o`/`O`, the error message appears and there's a new permanent task from null-ls. If that happens, fidget also "clones" the permanent tasks from null-ls to other language clients

![image](https://user-images.githubusercontent.com/889383/151126148-199da1ff-1f6e-4fd3-b60c-3731001c773b.png)

---

The second thing I noticed related to null-ls is that it seems to duplicate the tasks from other language servers (this time the message comes from the other language server and `null-ls` just copies it):

![image](https://user-images.githubusercontent.com/889383/151125769-f568cf6d-7324-45c1-a621-7a4ef759b3ea.png)

![image](https://user-images.githubusercontent.com/889383/151126235-2beb9c10-a330-4b9a-b9e3-311fb5ab961d.png)

**Comment by jose-elias-alvarez** [comment]
I suspect this is a null-ls issue that's caused by us calling the handler at a point where textlock prevents creating a window or setting buffer text. I put together a potential fix at jose-elias-alvarez/null-ls.nvim#619.

**Comment by j-hui** [comment]
Thanks @jose-elias-alvarez !

@Gelio let me know if that fixes the bug.

**Comment by Gelio** [comment]
@jose-elias-alvarez thanks for a quick fix!

The error message no longer appears and I can comfortably use fidget.nvim.

The only problem I see with null-ls now is that it duplicates tasks from other language servers:

![image](https://user-images.githubusercontent.com/889383/151305067-8d485d72-326d-44c4-a53a-bee545e256bd.png)

![image](https://user-images.githubusercontent.com/889383/151305283-87ac4ca3-0f69-4f15-8507-768fb2efb8ad.png)


I can open a new issue for that one to separate it from the problem with the error message.
