### ISSUE TITLE
Request: Make separate highlight for Fidget Spinner

### ISSUE THREAD

**Issue by ratheesh** [j-hui/fidget.nvim#92]
Currently, only highlights supported are `FidgetTitle` and `FidgetTask`.
Can we make a separate highlight for the Fidget spinner(eg: `FidgetSpinner`)?

**Comment by j-hui** [comment]
Sorry for the late reply. I haven't gotten any free time to do this, but I'll happily accept a PR

**Comment by j-hui** [comment]
Closed by #143
