### ISSUE TITLE
Use sane (but configurable) default path for debug logs

### ISSUE THREAD

**Issue by lcheylus** [j-hui/fidget.nvim#94]
I'm testing your plugin with different LSP servers (`sumneko` for Lua, `pyls` for Python). I have done some tests with debug logs activated : `debug.logging = true`

1. The path for logs in documentation (https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.md) is wrong : `~/.local/share/fidget.nvim.log` instead of `~/.local/share/nvim/fidget.nvim.log`.
2. It would be better if debug logs for fidget were in `~/.cache/nvim/` like other logs for Neovim.

**Comment by j-hui** [comment]
I think this is addressed by 41f327b somewhat, but I'll make a note of this for the upcoming rewrite.

**Comment by lcheylus** [comment]
OK, checked with the latest version of your plugin and configuration for full debug => logs are in `~/.cache/nvim/fidget.nvim.log`
