### ISSUE TITLE
API to enable, disable, hide, show fidget

### ISSUE THREAD

**Issue by mystilleef** [j-hui/fidget.nvim#96]
Can you provide an API to `enable`, `disable`, `hide`, and `show` fidget? 

This is useful for users who don't want any distractions in `InsertMode` or `ZenMode`.

**Comment by jim-at-jibba** [comment]
This would be awesome. CodeActions are spamming my screen at the moment

**Comment by mystilleef** [comment]
The overkill workaround is to detach LSP clients from the buffer on `InsertEnter`. Then reattach them on `InsertLeave`. 

However, I start LSP clients myself in `ftplugin`, and manage their setup and cleanup with `LspAttach` and `LspDetach`.

I'm not sure if this is practical for those who use an LSP manager like `lspconfig` for managing the clients.

This also won't work for folks who use LSP completion in `InsertMode`.

**Comment by j-hui** [comment]
Closed by #143
