### ISSUE TITLE
Disable fidget for null-ls gitsigns

### ISSUE THREAD

**Issue by shaun-mathew** [j-hui/fidget.nvim#99]
Currently, I have the following code for my null_ls configuration
```lua
local null_ls = require("null-ls")

null_ls.setup {
  sources = {
    null_ls.builtins.code_actions.gitsigns,
    ...
  }
}
```

I've added the following to my fidget setup:
```lua
sources = {
  ["null-ls"] = {
    ignore = true,
  },
},
```

which disables fidget for any null-ls sources, but I'd only like to disable them for the gitsigns plugin. Is there anyway to do this?

**Comment by j-hui** [comment]
There's no nice way to do this at the moment, but you can override the [fmt.task](https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.md#fmttask) handler to look for gitsigns in the task name or the message. If your handler returns false, no notification will be displayed.

Note that this feature isn't super extensively tested so please report back if you encounter any issues.

**Comment by Diaoul** [comment]
It would be great to have support for ignoring some tasks.
Something like this:
```sources.SOURCE_NAME.ignore_tasks = { "code_actions" }```

**Comment by Diaoul** [comment]
I tested with this config:
```lua
fmt = {
    task = function(task_name, message, percentage)
        if task_name == "code_action" then
            return false
        end
        return string.format(
            "%s%s [%s]",
            message,
            percentage and string.format(" (%s%%)", percentage) or "",
            task_name
        )
    end,
}
```

It ignores correctly the message in the output but still displays the spinner and name of the lsp even if there are no tasks to display.

**Comment by j-hui** [comment]
This is now doable either by returning `nil` from the `display.format_message()` handler, or by putting the language server name into the `ignores` option.

**Comment by sinkr** [comment]
Sorry to be dense, but I can't make this work no matter what I try:
```
return {
  "j-hui/fidget.nvim",
  config = function()
    require("fidget").setup({
      -- Options related to LSP progress subsystem
      progress = {
        poll_rate = 0, -- How and when to poll for progress messages
        suppress_on_insert = false, -- Suppress new messages while in insert mode
        ignore_done_already = false, -- Ignore new tasks that are already complete
        ignore_empty_message = false, -- Ignore new tasks that don't contain a message
        -- Clear notification group when LSP server detaches
        clear_on_detach = function(client_id)
          local client = vim.lsp.get_client_by_id(client_id)
          return client and client.name or nil
        end,
        -- How to get a progress message's notification group key
        notification_group = function(msg)
          return msg.lsp_client.name
        end,
        ignore = { "null_ls", "null-ls", "none-ls", "none_ls" }, -- List of LSP servers to ignore
(...)

```
